package com.sc4nam.module

import java.io.File
import io.github.memo33.metarules.meta.RotFlip
import syntax.RuleTransducer.TileOrientationCache

/** Manages the tile orientation cache. The cache is necessary to maintain
  * information about non-standard orientations:
  * In some situations, a tile can appear in other absolute orientations than
  * its symmetries might suggest.
  */
object RegenerateTileOrientationCache {
  val cacheFile = new File("src/main/resources/tileOrientationCache.txt")

  def main(args: Array[String]): Unit = apply()

  /** Regenerate the cache from scratch.
    */
  def apply(): Unit = {
    val tileOrientationCache = collection.mutable.Map.empty[Int, Set[RotFlip]]
    compileMetarulesUntilStable(tileOrientationCache)
    storeCache(tileOrientationCache)
  }

  /** Repeatedly compiles the metarule code until the cache does not get changed anymore.
    */
  def compileMetarulesUntilStable(cache: collection.mutable.Map[Int, Set[RotFlip]]): Unit = {
    val tileOrientationCache = TileOrientationCache(cache = cache, accum = collection.mutable.Map.empty[Int, Set[RotFlip]])
    var j = 0
    var stabilized = false
    val maxIter = 5
    while (j < 5 && !stabilized) {
      j += 1
      LOGGER.info(s"> metarules compilation: iteration $j")
      CompileAllMetarules.compileMetarulesOnce(tileOrientationCache)
      if (tileOrientationCache.accum.nonEmpty) {
        tileOrientationCache.cache ++= tileOrientationCache.accum
        tileOrientationCache.accum.clear()
        if (j == maxIter) {
          LOGGER.warning(s"Tile orientation cache could not be regenerated in $maxIter iterations. Increase the number of iterations or check if there is a bug.")
        }
      } else {
        stabilized = true
      }
    }
  }

  def storeCache(cache: collection.Map[Int, Set[RotFlip]]): Unit = {
    scala.util.Using.resource(new java.io.PrintWriter(cacheFile, "UTF-8")) { printer =>
      printer.println("; This file was generated by `sbt regenerateTileOrientationCache` and caches additional orientations of tiles.")
      printer.println("; Computing these orientations takes several runs of metarule compilation.")
      printer.println("; This file should be regenerated from time to time when the metarule code receives major updates.")
      for ((id, orientations) <- cache.toSeq.sortBy(_._1)) {
        printer.println(f"0x$id%08X," + orientations.mkString("+"))
      }
    }
  }

  def loadCache(): TileOrientationCache = {
    scala.util.Using.resource(new java.util.Scanner(cacheFile, "UTF-8")) { scanner =>
      val cache = collection.mutable.Map.empty[Int, Set[RotFlip]]
      while(scanner.hasNextLine()) {
        val line = scanner.nextLine()
        if (!line.startsWith(";") && line.nonEmpty) {
          val parts = line.split(",", 2)
          val id = java.lang.Long.parseLong(parts(0).substring(2), 16).toInt
          val orientations = RotFlip.ValueSet(parts(1).split("\\+").map(RotFlip.withName).toIndexedSeq*)
          cache(id) = orientations
        }
      }
      TileOrientationCache(cache = cache, accum = collection.mutable.Map.empty[Int, Set[RotFlip]])
    }
  }

  /** Loads the cache and gives a warning at the end if it was changed.
    */
  def withCache[U](body: TileOrientationCache => U): U = {
    val tileOrientationCache = loadCache()
    try {
      body(tileOrientationCache)
    } finally {
      if (tileOrientationCache.accum.nonEmpty) {
        LOGGER.warning(s"The file ${cacheFile} is outdated. Rebuild it with `sbt regenerateTileOrientationCache` and commit the changes.")
      }
    }
  }
}
