; Script generated by the HM NIS Edit Script Wizard.

; This defines compression method
SetCompressor /SOLID lzma

BrandingText "Network Addon Mod Setup"

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "Network Addon Mod"
!define PRODUCT_VERSION "Version 50 (Build 06)"
!define PRODUCT_PUBLISHER "NAM Team"
!define PRODUCT_WEB_SITE "http://www.sc4nam.com"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKCU"

; MUI 1.67 compatible ------
!include "UMUI.nsh"
!include "Sections.nsh"
!include "LogicLib.nsh"
!include "FileFunc.nsh"
!include "StrFunc.nsh"
!include "WinVer.nsh"
!include "nsDialogs.nsh"
!include "x64.nsh"
!include "MoveFileFolder.nsh"


;FileExists is already part of LogicLib, but returns true for directories as well as files
!macro _FileExists2 _a _b _t _f
	!insertmacro _LOGICLIB_TEMP
	StrCpy $_LOGICLIB_TEMP "0"
	StrCmp `${_b}` `` +4 0 ;if path is not blank, continue to next check
	IfFileExists `${_b}` `0` +3 ;if path exists, continue to next check (IfFileExists returns true if this is a directory)
	IfFileExists `${_b}\*.*` +2 0 ;if path is not a directory, continue to confirm exists
	StrCpy $_LOGICLIB_TEMP "1" ;file exists
	;now we have a definitive value - the file exists or it does not
	StrCmp $_LOGICLIB_TEMP "1" `${_t}` `${_f}`
!macroend
!undef FileExists
!define FileExists `"" FileExists2`
!macro _DirExists _a _b _t _f
	!insertmacro _LOGICLIB_TEMP
	StrCpy $_LOGICLIB_TEMP "0"	
	StrCmp `${_b}` `` +3 0 ;if path is not blank, continue to next check
	IfFileExists `${_b}\*.*` 0 +2 ;if directory exists, continue to confirm exists
	StrCpy $_LOGICLIB_TEMP "1"
	StrCmp $_LOGICLIB_TEMP "1" `${_t}` `${_f}`
!macroend
!define DirExists `"" DirExists`

!insertmacro Locate
 
Var /GLOBAL switch_overwrite


; Add splash screen
!define MUI_WELCOMEFINISHPAGE_BITMAP "nam50dev.bmp" ; the logo on the left of the first installer screen - 164x314 pixels by default - 171x373 for UMUI
!define UMUI_WELCOMEPAGE_TITLE_3LINES ; default is 2 lines, but 3 might be better if you have a long title
!define UMUI_FINISHPAGE_TITLE_3LINES
!define /IfNDef UMUI_LEFTIMAGE_BMP \
    "nam50dev.bmp"

; MUI Settings
!define UMUI_ABORTWARNING
!define UMUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define UMUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"
!define UMUI_HEADERIMAGE
!define UMUI_HEADERIMAGE_BITMAP_NOSTRETCH "NAM_logo.bmp" ; the logo in the top right corner of the other installer screens - 150x57 pixels by default
!define UMUI_HEADERIMAGE_RIGHT
!define MUI_COMPONENTSPAGE_SMALLDESC

; Language Selection Dialog Settings
!define UMUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define UMUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define UMUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!define UMUI_LICENSEPAGE_RADIOBUTTONS
!insertmacro MUI_PAGE_LICENSE "license_english.txt" ; a simple TXT file, keep it together with the BMP logos in the same folder where this installer script is located
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Components page
; !define MUI_PAGE_CUSTOMFUNCTION_LEAVE ComponentsLeave
!insertmacro MUI_PAGE_COMPONENTS
!define MUI_PAGE_CUSTOMFUNCTION_LEAVE MemoryPatches
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN
; !define MUI_FINISHPAGE_RUN_TEXT "Install/Start &Traffic Simulator Configuration Tool                   (also allows customization of new Data Views)"
; !define MUI_FINISHPAGE_RUN_FUNCTION "LaunchTSCT"
; !define MUI_FINISHPAGE_SHOWREADME "$INSTDIR\Documentation\1.README.htm" ; the path of your readme file, once it is installed
; !define MUI_PAGE_CUSTOMFUNCTION_PRE CheckTSCT
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"

; MUI end ------
Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "NetworkAddonMod_Setup_Version50_Build05.exe"
InstallDir "$DOCUMENTS\SimCity 4"
ShowInstDetails show
ShowUnInstDetails show

; Variables
Var SC4InstallDir
Var Memory
Var NAMAuxDir
Var Wine
Var SC4Exec
Var OSLang
Var SC4Docs

;Initializations

!insertmacro DirState
!insertmacro Locate
${StrStr}             ;This makes no sense at all.  But it's necessary...
; ${StrLoc}


; Setting pre-defined installation types
InstType "/CUSTOMSTRING=Click here for standard installation types"
InstType "Recommended (right-hand drive version)" ;InstType 1
InstType "Recommended (left-hand drive version)" ;InstType 2
InstType "Full installation (right-hand drive version)" ;InstType 3
InstType "Full installation (left-hand drive version)" ;InstType 4
InstType "Minimum installation (right-hand drive version)" ;InstType 5
InstType "Minimum installation (left-hand drive version)" ;InstType 6

; Defining Groups for the components selection page
Section "!Core NAM Files and Features" sec1 ; sec1 is a short name for description reference (see below)
SectionIn RO ; RO means read-only, so the user cannot deselect this
SectionIn 1 2 3 4 5 6 ; in which installation types (defined above) this section will show up
  ;Backs up any previous NAM install outside the Plugins folder
	StrCpy $switch_overwrite 0
	!insertmacro MoveFile "$INSTDIR\Plugins\NAM.dll" "$INSTDIR\Old NAM Backup\NAM.dll"
	!insertmacro MoveFolder "$INSTDIR\Plugins\Network Addon Mod" "$INSTDIR\Old NAM Backup\Network Addon Mod" "*.*"
	!insertmacro MoveFolder "$INSTDIR\Plugins\770-network-addon-mod" "$INSTDIR\Old NAM Backup\770-network-addon-mod" "*.*" ;sc4pac version
	
  ;Beginning of actual installation process
  SetOutPath "$INSTDIR\Plugins"
  File "NAM.dll"
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\1 Core"
  SetOverwrite ifnewer
  File "@4^1 Core\NetworkAddonMod_a_Controller_Marker.dat"
  File "@4^1 Core\NetworkAddonMod_a_EP1Paths.dat"
  File "@4^1 Core\NetworkAddonMod_BaseContent.dat"
  File "@4^1 Core\NetworkAddonMod_BaseContent_Textures.dat"
  File "@4^1 Core\NetworkAddonMod_Eraser.dat"
  File "@4^1 Core\NetworkAddonMod_Misc_Transit_Menu_Adjustment.dat"
  File "@4^1 Core\NetworkAddonMod_Monorail_Menu_Adjustment.dat"
  File "@4^1 Core\NetworkAddonMod_UI.dat"
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\1 Core\locale"
  File "@4^1 Core\locale\NetworkAddonMod_Locale_de.dat"
  File "@4^1 Core\locale\NetworkAddonMod_Locale_en.dat"
  File "@4^1 Core\locale\NetworkAddonMod_Locale_es.dat"
  File "@4^1 Core\locale\NetworkAddonMod_Locale_fr.dat"
  File "@4^1 Core\locale\NetworkAddonMod_Locale_it.dat"
  File "@4^1 Core\locale\NetworkAddonMod_Locale_ja.dat"
  File "@4^1 Core\locale\NetworkAddonMod_Locale_ko.dat"
  File "@4^1 Core\locale\NetworkAddonMod_Locale_nl.dat"
  File "@4^1 Core\locale\NetworkAddonMod_Locale_pt.dat"
  File "@4^1 Core\locale\NetworkAddonMod_Locale_sv.dat"
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Road, One-Way Road, and Avenue\Base Features"
  File "@52 Network Features\Road, One-Way Road, and Avenue#\^Base Features\*.dat"
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Street\Base Features"
  File "@52 Network Features\Street#\^Base Features\*.dat"
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Monorail\Base Features"
  File "@52 Network Features\Monorail#\^Base Features\*.dat"
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges"
  File "@57 Bridges\*.dat"
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\0-Road\Road"
  File "@57 Bridges\0-Road\Road\NetworkAddonMod_Road_Bridges_Bulk.dat"
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\6-Avenue\Avenue"
  File "@57 Bridges\6-Avenue\Avenue\NetworkAddonMod_Avenue_Bridges_Bulk.dat"
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\8-El-Rail\El-Rail"
  File "@57 Bridges\8-El-Rail\El-Rail\NetworkAddonMod_ElRail_Bridges_Bulk.dat"
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\a-One Way\One-way"
  File "@57 Bridges\a-One Way\One-way\NetworkAddonMod_One_Way_Bridges_Bulk.dat"
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\z-Bridge Controller"
  File "@57 Bridges\^z-Bridge Controller\NetworkAddonMod_Bridge_Controller.dat"
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\zz - Shared Resources"
  File "@57 Bridges\zz - Shared Resources\*.dat"
  File "@57 Bridges\zz - Shared Resources\*.SC4MODEL"
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\z_Common Files"
  File "@58 Texture and Drive Side Support\@2^z_Common Files\*.dat"
SectionEnd

/* Section "ReadMe Files" sec2
SectionIn RO ; documentation optimally should be installed. Note, if user doesnt install readme files the finsh page cant display the readme file.
SectionIn 1 2 3 4 5 6
  SetOutPath "$INSTDIR\Documentation"
  SetOverwrite ifnewer
  File "Documentation\1.README.htm"
  File "Documentation\2.InstallationInstructionsFile.htm"
  File "Documentation\3.ContentsFile.htm"
  File "Documentation\4.HistoryFile.htm"
  File "Documentation\5.TechnicalNotesFile.htm"
  File "Documentation\7.Q&A.htm"
  File "Documentation\9.CreditsFile.htm"
  File "Documentation\10B.Automata_Plugin_Files.htm"
  File "Documentation\10A.Traffic_Plugin_Files.htm"
  File "Documentation\10C.Data_View_Files.htm"
  SetOutPath "$INSTDIR\Documentation\images"
  SetOverwrite ifnewer
  File "Documentation\images\diagonal_streets.jpg"
  File "Documentation\images\diagonal_streets2.jpg"
  File "Documentation\images\draggable_glr.jpg"
  File "Documentation\images\glr_puzzle_pieces.jpg"
  File "Documentation\images\oneway_puzzle_pieces.jpg"
  File "Documentation\images\oneway_roundabout.jpg"
  File "Documentation\images\ped_malls.jpg"
  File "Documentation\images\puzzle_pieces.jpg"
  File "Documentation\images\road_roundabout.jpg"
  File "Documentation\images\traffic_volume_view.jpg"
SectionEnd
*/

SectionGroup /e "!NAM Controller (select one)" sec3
; SectionIn RO
; SectionEnd

Section "NAM Right Hand Traffic (RHT) Controller" controller1
SectionIn 1 3 5
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\0 NAM Controller_RHD"
  SetOverwrite ifnewer
  File "@0=0 NAM Controller_RHD_4GB_Full\NetworkAddonMod_Controller.dat"
  File "@0=0 NAM Controller_RHD_4GB_Full\NetworkAddonMod_IndividualNetworkRULs_RHD.dat"
SectionEnd

Section /o "NAM Left Hand Traffic (LHT) Controller" controller2
SectionIn 2 4 6
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\0 NAM Controller_LHD"
  SetOverwrite ifnewer
  File "@1-0 NAM Controller_LHD_4GB_Full\NetworkAddonMod_Controller.dat"
  File "@1-0 NAM Controller_LHD_4GB_Full\NetworkAddonMod_IndividualNetworkRULs_LHD.dat"
SectionEnd

Section -dummy controller3
SectionIn 7
SectionEnd
SectionGroupEnd

;Section "!Traffic Simulator Capacity Level (select one)" sec11
;SectionIn RO
;SectionEnd

SectionGroup /e "Traffic Simulator Capacity (select one)" sec11
Section /o "NAM Simulator Classic" capa1
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\9 Traffic Simulator"
  SetOverwrite ifnewer
  File "@59 Traffic Simulator#\@1-Classic (Original Maxis Capacity - Lowest Capacity)\NetworkAddonMod_Traffic_Plugin_Z_Classic.dat"
  File "@59 Traffic Simulator#\@1-Classic (Original Maxis Capacity - Lowest Capacity)\NetworkAddonMod_Volume_Data_View_Z_Classic.dat"
  File "@59 Traffic Simulator#\@1-Classic (Original Maxis Capacity - Lowest Capacity)\NetworkAddonMod_TrafficSimCapacityMarker_Classic.dat"
SectionEnd

Section "NAM Simulator Low" capa2
SectionIn 1 2 3 4 5 6
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\9 Traffic Simulator"
  SetOverwrite ifnewer
  File "@59 Traffic Simulator#\@2=Low (Recommended)\NetworkAddonMod_Traffic_Plugin_Z_Low.dat"
  File "@59 Traffic Simulator#\@2=Low (Recommended)\NetworkAddonMod_Volume_Data_View_Z_Low.dat"
  File "@59 Traffic Simulator#\@2=Low (Recommended)\NetworkAddonMod_TrafficSimCapacityMarker_Low.dat"
SectionEnd

Section /o "NAM Simulator Medium" capa3
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\9 Traffic Simulator"
  SetOverwrite ifnewer
  File "@59 Traffic Simulator#\@3-Medium\NetworkAddonMod_Traffic_Plugin_Z_Medium.dat"
  File "@59 Traffic Simulator#\@3-Medium\NetworkAddonMod_Volume_Data_View_Z_Medium.dat"
  File "@59 Traffic Simulator#\@3-Medium\NetworkAddonMod_TrafficSimCapacityMarker_Medium.dat"
SectionEnd

Section /o "NAM Simulator High" capa4
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\9 Traffic Simulator"
  SetOverwrite ifnewer
  File "@59 Traffic Simulator#\@4-High\NetworkAddonMod_Traffic_Plugin_Z_High.dat"
  File "@59 Traffic Simulator#\@4-High\NetworkAddonMod_Volume_Data_View_Z_High.dat"
  File "@59 Traffic Simulator#\@4-High\NetworkAddonMod_TrafficSimCapacityMarker_High.dat"
SectionEnd

Section /o "NAM Simulator Ultra" capa5
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\9 Traffic Simulator"
  SetOverwrite ifnewer
  File "@59 Traffic Simulator#\@5-Ultra (Highest Capacity)\NetworkAddonMod_Traffic_Plugin_Z_Ultra.dat"
  File "@59 Traffic Simulator#\@5-Ultra (Highest Capacity)\NetworkAddonMod_Volume_Data_View_Z_Ultra.dat"
  File "@59 Traffic Simulator#\@5-Ultra (Highest Capacity)\NetworkAddonMod_TrafficSimCapacityMarker_Ultra.dat"
SectionEnd
SectionGroupEnd

SectionGroup /e "!Automata Controller Files (select one)" sec10
Section /o "Standard" auto1
SectionIn 1 2 3 4 5 6
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\4 Automata Controller"
  SetOverwrite ifnewer
  File "@54 Automata Controller#\@1-Standard\NetworkAddonMod_Automata_Plugin_Standard.dat"
SectionEnd

Section /o "Standard 24-Hour" auto2
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\4 Automata Controller"
  SetOverwrite ifnewer
  File "@54 Automata Controller#\@2-Standard 24-Hour\NetworkAddonMod_Automata_Plugin_Automata24.dat"
SectionEnd

Section "Standard Persistent" auto3
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\4 Automata Controller"
  SetOverwrite ifnewer
  File "@54 Automata Controller#\@3=Standard Persistent\NetworkAddonMod_Automata_Plugin_Standard_Persist.dat"
SectionEnd

Section /o "Standard Persistent 24-Hour" auto4
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\4 Automata Controller"
  SetOverwrite ifnewer
  File "@54 Automata Controller#\@4-Standard Persistent 24-Hour\NetworkAddonMod_Automata_Plugin_Automata24_Persist.dat"
SectionEnd

Section /o "Radical" auto5
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\4 Automata Controller"
  SetOverwrite ifnewer
  File "@54 Automata Controller#\@5-Radical\NetworkAddonMod_Automata_Plugin_Radical.dat"
SectionEnd

Section /o "Radical 24-Hour" auto6
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\4 Automata Controller"
  SetOverwrite ifnewer
  File "@54 Automata Controller#\@6-Radical 24-Hour\NetworkAddonMod_Automata_Plugin_Radical_Automata24.dat"
SectionEnd

Section /o "Radical Persistent" auto7
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\4 Automata Controller"
  SetOverwrite ifnewer
  File "@54 Automata Controller#\@7-Radical Persistent\NetworkAddonMod_Automata_Plugin_Radical_Persist.dat"
SectionEnd

Section /o "Radical Persistent 24-Hour" auto8
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\4 Automata Controller"
  SetOverwrite ifnewer
  File "@54 Automata Controller#\@8-Radical Persistent 24-Hour\NetworkAddonMod_Automata_Plugin_Radical_Automata24_Persist.dat"
SectionEnd

Section /o "LB Radical Persistent 24-Hour" auto9
  SetOutPath "$INSTDIR\Plugins\Network Addon Mod\4 Automata Controller"
  SetOverwrite ifnewer
;  Delete $OUTDIR\NetworkAddonMod_Automata_Plugin_*.dat
  File "@54 Automata Controller#\@9-LB Radical Persistent 24-Hour\NAM_LB_Automata_Plugin_Radical_Automata24_Persist.dat"
SectionEnd
SectionGroupEnd

SectionGroup /e "!Network Features and Additions" sec4
	SectionGroup "!Surface Roadway Features" roamain
		Section "Draggable Elevated Viaducts" roavia1
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Road, One-Way Road, and Avenue"
				;includes resources for puzzle piece viaducts for seamless legacy support
			File "@52 Network Features\Road, One-Way Road, and Avenue#\Elevated Viaducts\NetworkAddonMod_RoadViaducts_*.dat"
		SectionEnd
		Section "Legacy Elevated Viaduct Puzzle Pieces" roavia2
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Road, One-Way Road, and Avenue"
			File "@52 Network Features\Road, One-Way Road, and Avenue#\Elevated Viaducts\Legacy Puzzle Piece Menu Access\NetworkAddonMod_Legacy_RoadViaductPuzzlePieceButtons.dat"
		SectionEnd
		Section "Alternate Elevated Viaducts" roavia3
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Road, One-Way Road, and Avenue"
			File "@52 Network Features\Road, One-Way Road, and Avenue#\Elevated Viaducts\Viaduct Additions\*.dat"
		SectionEnd
		SectionGroup "Network Widening Mod and Turning Lanes" nwmturn
			Section "Network Widening Mod" nwm
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Road, One-Way Road, and Avenue"
				File "@52 Network Features\Road, One-Way Road, and Avenue#\Network Widening Mod and Turn Lanes\NetworkWideningMod_*.dat"
				File "@52 Network Features\Road, One-Way Road, and Avenue#\Network Widening Mod and Turn Lanes\NetworkAddonMod_Roundabouts_Turbo_Plugin.dat"
				File "@52 Network Features\Road, One-Way Road, and Avenue#\Network Widening Mod and Turn Lanes\NetworkAddonMod_TurningLanes_OneWayRoadSignalization_Plugin.dat"
			SectionEnd

			Section "RealExpressway (REW) Ramp System" rew
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Road, One-Way Road, and Avenue"
				File "@52 Network Features\Road, One-Way Road, and Avenue#\RealExpressway\*.dat"
				File "@52 Network Features\Road, One-Way Road, and Avenue#\RealExpressway\RealExpressway_FLEX_Piece\1_Paths\*.dat"
				File "@52 Network Features\Road, One-Way Road, and Avenue#\RealExpressway\RealExpressway_FLEX_Piece\Z_Rotation_Ring_Files\*.dat"
			SectionEnd
			Section /o "Legacy Turn Lane Extension Pieces (TuLEPs)" tulep
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Road, One-Way Road, and Avenue"
				File "@52 Network Features\Road, One-Way Road, and Avenue#\Network Widening Mod and Turn Lanes\NetworkAddonMod_TurningLanes_Extension_*.dat" 
				File "@52 Network Features\Road, One-Way Road, and Avenue#\!Legacy Turn Lane Extension Piece (TuLEP) Menu Access\NetworkAddonMod_TuLEP_LegacyButtons.dat"		
			SectionEnd
			Section /o "Legacy Auto Avenue Turn Lanes" atl
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Road, One-Way Road, and Avenue"
				File "@52 Network Features\Road, One-Way Road, and Avenue#\!Legacy Auto Avenue Turn Lanes\NetworkAddonMod_TurningLanes_Avenues_Plugin_INRULs.dat" 
			SectionEnd
			Section "Flexible Turn Lanes (FTLs)" ftl
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Road, One-Way Road, and Avenue"
				File "@52 Network Features\Road, One-Way Road, and Avenue#\Network Widening Mod and Turn Lanes\NetworkAddonMod_TurningLanes_Flexible.dat"
				 ;legacy support without menu buttons
				${Unless} ${SectionIsSelected} ${tulep}
				File "@52 Network Features\Road, One-Way Road, and Avenue#\Network Widening Mod and Turn Lanes\NetworkAddonMod_TurningLanes_Extension_*.dat"
				${EndIf}
			SectionEnd
			Section "Network Widening Mod Bridges" nwmbridgemain
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\0-Road\NWM"
				File "@57 Bridges\0-Road\NWM\*.dat"
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\6-Avenue\NWM"
				File "@57 Bridges\6-Avenue\NWM\*.dat"
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\a-One Way\NWM"
				File "@57 Bridges\a-One Way\NWM\*.dat"
			SectionEnd
		SectionGroupEnd
		SectionGroup "Street Addon Mod Features" sammain
			Section "Street Addon Mod" sam
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Street"
				File "@52 Network Features\Street#\Street Addon Mod\*.dat"
			SectionEnd
			Section "Street Addon Mod Bridges" sambridgemain
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\3-Street\SAM"
				File "@57 Bridges\3-Street\SAM\*.dat"
			SectionEnd
		SectionGroupEnd
		Section "Rural Roads Plugin (RuRP)" rurp
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Road, One-Way Road, and Avenue"
			File "@52 Network Features\Road, One-Way Road, and Avenue#\Rural Roads Plugin\NetworkAddonMod_Rural_Roads_*.dat" 
		SectionEnd
		SectionGroup "One-Way Road Arrow Plugins" owrarrowmain
			Section "Default One-Way Road Arrows" owrarrow1
			SectionEnd
			Section /o "One-Way Road Arrow Removal" owrarrow2
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Road, One-Way Road, and Avenue"
				File "@52 Network Features\Road, One-Way Road, and Avenue#\!One-Way Road Arrow Plugins\=One-Way Road Arrow Elimination\*.dat" 
			SectionEnd
			Section /o "One-Way Road Arrow Reduction" owrarrow3
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Road, One-Way Road, and Avenue"
				File "@52 Network Features\Road, One-Way Road, and Avenue#\!One-Way Road Arrow Plugins\-One-Way Road Arrow Reduction\*.dat" 
			SectionEnd
			Section /o "One-Way Road Single Arrow" owrarrow4
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Road, One-Way Road, and Avenue"
				File "@52 Network Features\Road, One-Way Road, and Avenue#\!One-Way Road Arrow Plugins\Single Arrows for One-Way Roads\*.dat" 			
			SectionEnd
		SectionGroupEnd
		Section "Additional Street Bridges" streetbridgemain
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\3-Street\Street"
			File "@57 Bridges\3-Street\Street\*.dat"
		SectionEnd
		Section "Additional Road Bridges" roadbridgemain
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\0-Road\Road"
			File "@57 Bridges\0-Road\Road\*.dat"
		SectionEnd
		Section "Additional One-Way Road Bridges" owrbridgemain
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\a-One Way\One-way"
			File "@57 Bridges\a-One Way\One-way\*.dat"
		SectionEnd
		Section "Additional Avenue Bridges" avebridgemain
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\6-Avenue\Avenue"
			File "@57 Bridges\6-Avenue\Avenue\*.dat"
		SectionEnd
		/* Verbose versions that allow specific bridges to be installed/not installed
		SectionGroupEnd
		SectionGroup "Additional Street Bridges" streetbridgemain
			Section "Blue Suspension Street Bridge" streetbridge1
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\3-Street\Street"
			SectionEnd
			Section "Covered Street Bridge" streetbridge2
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\3-Street\Street"
			SectionEnd
			Section "Green Truss Street Bridge" streetbridge3
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\3-Street\Street"
			SectionEnd
			Section "IDS2 V-Shaped Steel Girder Street Bridge" streetbridge4
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\3-Street\Street"
			SectionEnd
			Section "Concrete Street Bridge" streetbridge5
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\3-Street\Street"
			SectionEnd
			Section "Level Street Bridge" streetbridge6
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\3-Street\Street"
			SectionEnd
			Section "Pont Neuf Street Bridge" streetbridge7
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\3-Street\Street"
			SectionEnd
			Section "Rural Street Bridge" streetbridge8
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\3-Street\Street"
			SectionEnd
			Section "Red Truss Street Bridge" streetbridge9
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\3-Street\Street"
			SectionEnd
			Section "Steel Girder Street Bridge" streetbridge10
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\3-Street\Street"
			SectionEnd
			Section "Yellow Steel Girdder Street Bridge" streetbridge11
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\3-Street\Street"
			SectionEnd
		SectionGroupEnd
		SectionGroup "Additional Road Bridges" roadbridgemain
		SectionGroupEnd
		SectionGroup "Additional One-Way Road Bridges" owrbridgemain
		SectionGroupEnd
		SectionGroup "Additional Avenue Bridges" avebridgemain
		SectionGroupEnd
		*/
		Section /o "Wide Corner Road and One-Way Road Diagonal Intersections" widecrn
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Road, One-Way Road, and Avenue"
			File "@52 Network Features\Road, One-Way Road, and Avenue#\!Wide Corner Road and One-Way Road DxD Intersections\NetworkAddonMod_WideCorner_DxD_Intersections.dat" 
		SectionEnd
	SectionGroupEnd
	
	SectionGroup "!Rail (RealRailway/RRW)" rail
		Section "RealRailway (RRW) Standard" rrw
			SectionIn RO
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\z_Rail (RealRailway)\0_Rail_Legacy"
			File "@52 Network Features\^z_Rail (RealRailway)\0_Rail_Legacy#\1_Curves\*.dat"
			File "@52 Network Features\^z_Rail (RealRailway)\0_Rail_Legacy#\2_Railway Addon Mod\*.dat"
			File "@52 Network Features\^z_Rail (RealRailway)\0_Rail_Legacy#\3_Rail Viaducts\*.dat"
			File "@52 Network Features\^z_Rail (RealRailway)\0_Rail_Legacy#\5_Legacy_Textures_RRW\*.dat"
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\z_Rail (RealRailway)\a_RealRailway_Core"
			File "@52 Network Features\^z_Rail (RealRailway)\a_RealRailway_Core\*.dat"
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\z_Rail (RealRailway)\c_RealRailway_Tunnel"
			File "@52 Network Features\^z_Rail (RealRailway)\c_RealRailway_Tunnel\*.dat"
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\z_Rail (RealRailway)\e_RealRailway_Props"
			File "@52 Network Features\^z_Rail (RealRailway)\e_RealRailway_Props\*.dat"
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\z_Rail (RealRailway)\g_RealRailway_Stations\Brenda_Xne Modern L2 Viaduct Rail Station"
			File "@52 Network Features\^z_Rail (RealRailway)\g_RealRailway_Stations\Brenda_Xne Modern L2 Viaduct Rail Station\*.dat"
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\z_Rail (RealRailway)\g_RealRailway_Stations\Xyloxadoria Modern Diagonal L2 Viaduct Rail Station"
			File "@52 Network Features\^z_Rail (RealRailway)\g_RealRailway_Stations\Xyloxadoria Modern Diagonal L2 Station\*.dat"
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\z_Rail (RealRailway)\h_RealRailway_ABE_Bridges"
			File "@52 Network Features\^z_Rail (RealRailway)\h_RealRailway_ABE_Bridges\*.dat"
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\z_Rail (RealRailway)\z_RealRailway_Textures"
			File "@52 Network Features\^z_Rail (RealRailway)\z_RealRailway_Textures\*.dat"
		SectionEnd
		Section "Optional RealRailway (RRW) Legacy Support for Pre-RRW Items" rrwpre
			File "@52 Network Features\^z_Rail (RealRailway)\0_Rail_Legacy#\6_Optional_Legacy_PreRRW\zOptional_RealRailway_Textures_Legacy_PreRRW.dat"
		SectionEnd
		SectionGroup "RealRailway Slope Settings" rrwslopemain
			Section "Default Slope Settings" rrwslope1
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\RRW Tunnel and Slope Parameters#"
			File "@52 Network Features\RRW Tunnel and Slope Parameters#\@1-Maxis Default\*.dat"
			SectionEnd
			Section /o "Moderate Slope Settings" rrwslope2
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\RRW Tunnel and Slope Parameters#"
			File "@52 Network Features\RRW Tunnel and Slope Parameters#\@2=Moderate\*.dat"
			SectionEnd
			Section /o "Strict Slope Settings" rrwslope3
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\RRW Tunnel and Slope Parameters#"
			File "@52 Network Features\RRW Tunnel and Slope Parameters#\@3-Strict\*.dat"
			SectionEnd
		SectionGroupEnd
		Section "Underground Rail (URail)" urail
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\z_Rail (RealRailway)\0_Rail_Legacy"
			File "@52 Network Features\^z_Rail (RealRailway)\0_Rail_Legacy#\4_Underground Rail\*.dat"
		SectionEnd
		Section "Additional Rail Bridges" railbridgemain
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\1-Rail\Maxis"
			File "@57 Bridges\1-Rail\Maxis\*.dat"
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\1-Rail\Maxis Bridge Overrides"
			File "@57 Bridges\1-Rail\Maxis Bridge Overrides\*.dat"
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\1-Rail\Rail Viaduct Bridges"
			File "@57 Bridges\1-Rail\Rail Viaduct Bridges\*.dat"
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\1-Rail\RRW"
			File "@57 Bridges\1-Rail\RRW\*.dat"
		SectionEnd
	SectionGroupEnd
	
	SectionGroup "!RealHighway (RHW)" rhw
		Section "Base Features and Network Tool" rhwbase
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\RealHighway"
			File "@52 Network Features\RealHighway#\^Base Features and Network Tool\*.dat"
			File "@52 Network Features\RealHighway#\RHW Double-Deck Networks\*.dat"
			File "@52 Network Features\RealHighway#\RHW FLEXFly\*.dat"
			File "@52 Network Features\RealHighway#\RHW Small Networks and Ramps\*.dat"
			File "@52 Network Features\RealHighway#\RHW Wider C-Type Networks\*.dat"
			File "@52 Network Features\RealHighway#\RHW Wider S-Type Networks\*.dat"
			File "@52 Network Features\RealHighway#\Special Intersection Pieces\*.dat"
			File "@52 Network Features\RealHighway#\Three-Level Crossings\*.dat"
			File "@52 Network Features\RealHighway#\RHW FLEX Turn Lanes\*.dat"
		SectionEnd
		Section "Regional Transportation View Support for RHW" rhwreg
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\RealHighway"
			File "@52 Network Features\RealHighway#\RHW Regional Transport Map Plugin\*.dat"
		SectionEnd
		Section "RHW Cosmetic Pieces" rhwcp
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\RealHighway"
			File "@52 Network Features\RealHighway#\RHW Cosmetic Pieces\*.dat"
		SectionEnd
		Section "Bus Rapid Transit Support" rhwbrt
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\RealHighway"
			File "@52 Network Features\RealHighway#\Bus Rapid Transit Support\Bus Filters for L0 RHW-2\*.dat"
			File "@52 Network Features\RealHighway#\Bus Rapid Transit Support\E-N BriPizza L2 Elevated Road Bus Stop\*.dat"
			File "@52 Network Features\RealHighway#\Bus Rapid Transit Support\Xyloxadoria Modern Arch BRT Station\*.dat"
		SectionEnd
		Section "RHW Legacy Support Plugin" rhwlegacy
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\RealHighway"
			File "@52 Network Features\RealHighway#\a_Legacy Support#\^Primary Legacy Support\*.dat"
		SectionEnd
		Section /o "RHW Legacy Puzzle Pieces" rhwpuzzle
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\RealHighway"
			File "@52 Network Features\RealHighway#\a_Legacy Support#\!Legacy Puzzle Piece Menu Buttons\*.dat"
		SectionEnd
		Section "RHW FLUPs Legacy Support" rhwflupleg
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\RealHighway"
			File "@52 Network Features\RealHighway#\a_Legacy Support#\RHW FLUPs Legacy Support\*.dat"
		SectionEnd
		Section "RHW Bridges" rhwbridgemain
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\b-Real Highway"
			File "@57 Bridges\b-Real Highway\*.dat"
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\c-Ground Highway"
			File "@57 Bridges\c-Ground Highway\RHW\*.dat"	
		SectionEnd
	SectionGroupEnd
	
	
	SectionGroup "!Pedestrian Malls and Paths" ped
		Section "Draggable Classic Pedestrian Malls" ped1
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Pedestrian Malls and Paths"
			File "@52 Network Features\Pedestrian Malls and Paths#\NAMSC4_Classic_DragPedmalls_*.dat"
		SectionEnd
		Section "Pedestrian Mall and Elevated Walkway Puzzle Pieces" ped2
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Pedestrian Malls and Paths"
			File "@52 Network Features\Pedestrian Malls and Paths#\NetworkAddonMod_PedMalls.dat"
			File "@52 Network Features\Pedestrian Malls and Paths#\NetworkAddonMod_PedMalls_Textures.dat"
		SectionEnd
		Section "Mid-Block Crosswalks" midblock
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Pedestrian Malls and Paths"
			File "@52 Network Features\Pedestrian Malls and Paths#\Midblock Crosswalks#\*.dat"
		SectionEnd
		Section "PedMall Bridges" pedbridgemain
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\3-Street\PRM"
			File "@57 Bridges\3-Street\PRM\*.dat"
		SectionEnd
	SectionGroupEnd
	
	Section "Hybrid Railway Plugin" hrw
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Hybrid Railway (RRW-RHSR)\a_HybridRailway_Icons_Previews"
		File "@52 Network Features\Hybrid Railway (RRW-RHSR)\a_HybridRailway_Icons_Previews\*.dat"
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Hybrid Railway (RRW-RHSR)\b_HybridRailway_Exemplars"
		File "@52 Network Features\Hybrid Railway (RRW-RHSR)\b_HybridRailway_Exemplars\*.dat"
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Hybrid Railway (RRW-RHSR)\c_Hybrid Railway_Models"
		File "@52 Network Features\Hybrid Railway (RRW-RHSR)\c_Hybrid Railway_Models\*.dat"
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Hybrid Railway (RRW-RHSR)\d_HybridRailway_Textures"
		File "@52 Network Features\Hybrid Railway (RRW-RHSR)\d_HybridRailway_Textures\*.dat"
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Hybrid Railway (RRW-RHSR)\e_HybridRailway_Fittings\HybridRailway_Catenary"
		File "@52 Network Features\Hybrid Railway (RRW-RHSR)\e_HybridRailway_Fittings\HybridRailway_Catenary\*.dat"
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Hybrid Railway (RRW-RHSR)\f_HybridRailway_Stations\Hybrid Rail Station v1 - Dual Network (RRW-RHSR)"
		File "@52 Network Features\Hybrid Railway (RRW-RHSR)\f_HybridRailway_Stations\Hybrid Rail Station v1 - Dual Network (RRW-RHSR)\*.dat"
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Hybrid Railway (RRW-RHSR)\f_HybridRailway_Stations\Hybrid Rail Station v2 - RRW ONLY"
		File "@52 Network Features\Hybrid Railway (RRW-RHSR)\f_HybridRailway_Stations\Hybrid Rail Station v2 - RRW ONLY\*.dat"
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\9-Monorail\HybridRailway Bridges"
		File "@57 Bridges\9-Monorail\HybridRailway Bridges\*.dat"
	SectionEnd
	
	SectionGroup "!Light Rail/Tram" lightrail
		Section "Ground Light Rail (GLR)/Tram - Draggable" glr1
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Light Rail"
			File "@52 Network Features\Light Rail#\Ground Light Rail\NetworkAddonMod_GroundLightRail_Plugin_INRULs.dat"
			File "@52 Network Features\Light Rail#\Ground Light Rail\NetworkAddonMod_GroundLightRailDrag_*.dat"
			File "@52 Network Features\Light Rail#\Ground Light Rail\GLR Stations\NOB Ortho Tram Station\*.dat"
			File "@52 Network Features\Light Rail#\Ground Light Rail\GLR Stations\NOB Diagonal Tram Station\*.dat"
		SectionEnd
		Section "Ground Light Rail (GLR)/Tram - Puzzle Pieces" glr2
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Light Rail"
			File "@52 Network Features\Light Rail#\Ground Light Rail\NetworkAddonMod_GroundLightRail_Plugin.dat"
			File "@52 Network Features\Light Rail#\Ground Light Rail\NetworkAddonMod_GroundLightRail_Plugin_Textures.dat"
			${Unless} ${SectionIsSelected} ${glr1}
			File "@52 Network Features\Light Rail#\Ground Light Rail\GLR Stations\NOB Ortho Tram Station\*.dat"
			File "@52 Network Features\Light Rail#\Ground Light Rail\GLR Stations\NOB Diagonal Tram Station\*.dat"
			${EndIf}	
		SectionEnd
		Section /o "Additional Ground Light Rail Styles" glr3
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Light Rail"
			File "@52 Network Features\Light Rail#\Ground Light Rail\Ground Light Rail Extended Styles\*.dat"
		SectionEnd
		Section "Elevated Light Rail Dual-Networking" elrdual
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Light Rail"
			File "@52 Network Features\Light Rail#\Elevated Light Rail Dual-Networking\*.dat"
		SectionEnd
		Section "Ground Light Rail/Tram Dual-Networking" glrdual
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Light Rail"
			File "@52 Network Features\Light Rail#\Ground Light Rail Dual-Networking\*.dat"
		SectionEnd
		Section "High Elevated Rail Puzzle Pieces" highelr
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Light Rail"
			File "@52 Network Features\Light Rail#\High Elevated Light Rail Puzzle Pieces\*.dat"
		SectionEnd
		Section "Additional Light Rail and Dual-Networking Bridges" lightrailbridgemain
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\8-El-Rail\El-Rail"
			File "@57 Bridges\8-El-Rail\El-Rail\*.dat"				
			${If} ${SectionIsSelected} ${glr1}
			${OrIf} ${SectionIsSelected} ${glr2}
			${OrIf} ${SectionIsSelected} ${glrdual}
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\8-El-Rail\GLR"
				File "@57 Bridges\8-El-Rail\GLR\NetworkAddonMod_GLR_Bridges_Bulk.dat"				
				File "@57 Bridges\8-El-Rail\GLR\NetworkAddonMod_Cable_Stayed_GLR_Bridge.dat"				
			${EndIf}
			${If} ${SectionIsSelected} ${glrdual}		
				SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\8-El-Rail\GLR"
				File "@57 Bridges\8-El-Rail\GLR\NetworkAddonMod_Pont_Notre_Dame_TIR.dat"				
			${EndIf}
		SectionEnd
	SectionGroupEnd
	
	SectionGroup "!Monorail and Override Networks" monorail
		Section "Additional Monorail Bridges" monorailbridgemain
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\9-Monorail\Monorail"
			File "@57 Bridges\9-Monorail\Monorail\NetworkAddonMod_AITPier_Monorail_Bridge.dat"
			File "@57 Bridges\9-Monorail\Monorail\NetworkAddonMod_Cable_Stayed_Monorail_Bridge.dat"
			File "@57 Bridges\9-Monorail\Monorail\NetworkAddonMod_Monorail_Suspension_Bridge.dat"
			File "@57 Bridges\9-Monorail\Monorail\NetworkAddonMod_YPier_Monorail_Bridge.dat"
		SectionEnd
		Section "High Speed Rail Project (HSRP) (semi-legacy)" hsrp
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Monorail\High Speed Rail Project"
			File "@52 Network Features\Monorail#\High Speed Rail Project\*.dat"	
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Monorail\High Speed Rail Project\High Speed Rail Stations"
			File "@52 Network Features\Monorail#\High Speed Rail Project\High Speed Rail Stations\Xyloxadoria Modern Arched L0 High Speed Rail (GHSR) Station.SC4Lot.dat"
			File "@52 Network Features\Monorail#\High Speed Rail Project\High Speed Rail Stations\Xyloxadoria Modern Arched L2 High Speed Rail (HSR) Station.SC4Lot.dat"	
			File "@52 Network Features\Monorail#\High Speed Rail Project\High Speed Rail Stations\Xyloxadoria Modern Diagonal L2 HSR Station.SC4Lot.dat"
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\9-Monorail\HSR v1"
			File "@57 Bridges\9-Monorail\HSR v1\*.dat"
		SectionEnd
		Section "High Monorail Puzzle Pieces" highmon
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\9-Monorail\Monorail"
			File "@57 Bridges\9-Monorail\Monorail\NetworkAddonMod_HighElevatedMonorailBridge.dat"
		SectionEnd
	SectionGroupEnd
	
	SectionGroup "!Maxis Highway Options (select one)" mhw
	Section "Default Maxis Highway Additonal Features" mhw1
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Maxis Highway\Default Style"
		File "@52 Network Features\Maxis Highway#\@1=Default Style\^Base Features\*.dat"
	SectionEnd
	Section /o "Maxis Highway Override (MHO)" mhw2
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Maxis Highway\Maxis Highway Override (RHW-Style)"
		File "@52 Network Features\Maxis Highway#\@2-Maxis Highway Override (RHW-Style)\*.dat"
		${Unless} ${SectionIsSelected} ${rhwbase}
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\RealHighway"
			File "@52 Network Features\RealHighway#\^Base Features and Network Tool\RealHighway_Core.dat"
			File "@52 Network Features\RealHighway#\^Base Features and Network Tool\RealHighway_RHW-2.dat"
			File "@52 Network Features\RealHighway#\^Base Features and Network Tool\RealHighway_Props.dat"
			File "@52 Network Features\RealHighway#\RHW Small Networks and Ramps\RealHighway_MIS.dat"
			File "@52 Network Features\RealHighway#\RHW Small Networks and Ramps\RealHighway_RHW-4.dat"
		${EndIf}
	SectionEnd
	Section -dummy mhw3
	SectionIn 7
	SectionEnd
	Section "Maxis Highway Additional Bridges" mhwbridgemain
		${If} ${SectionIsSelected} ${mhw1}
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\2-El-Highway"
		File "@57 Bridges\2-El-Highway\*.dat"			
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\c-Ground Highway\Ground Highway"
		File "@57 Bridges\c-Ground Highway\Ground Highway\*.dat"			
		${EndIf}
		${If} ${SectionIsSelected} ${mhw2}
			${Unless} ${SectionIsSelected} ${rhwbase}
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\7 Bridges\c-Ground Highway"
			File "@57 Bridges\c-Ground Highway\RHW\*.dat"	
			${EndIf}
		${EndIf}
	SectionEnd
	SectionGroupEnd
	
	SectionGroup "!Subway and Underground (FLUPs)" subflups
		Section "Flexible Underpass (FLUPs) Puzzle Pieces" flups1
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Subway and FLUPs"
			File "@52 Network Features\Subway and FLUPs#\Flexible Underpasses (FLUPs)\NetworkAddonMod_FlexibleUnderpasses_SubwayDraggable.dat"
			File "@52 Network Features\Subway and FLUPs#\Flexible Underpasses (FLUPs)\NetworkAddonMod_FlexibleUnderpasses_SubwayDraggable_Textures.dat"
		SectionEnd
		Section "Subway-Based Draggable FLUPs" flups2
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Subway and FLUPs"
			File "@52 Network Features\Subway and FLUPs#\Flexible Underpasses (FLUPs)\NetworkAddonMod_FLUPs_*.dat"
		SectionEnd
	SectionGroupEnd
	
	SectionGroup "!Canal Addon Mod (CAN-AM)" watertransport
		Section /o "Canal Addon Mod (CAN-AM) - Callagrafx Canals" canam1
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Water Transport"
			File "@52 Network Features\Water Transport#\Canal Addon Mod#\NetworkAddonMod_CanAM_*.dat"
			File "@52 Network Features\Water Transport#\Canal Addon Mod#\@1=Callagrafx Style\CanAM Props CAL\*.dat"
			File "@52 Network Features\Water Transport#\Canal Addon Mod#\@1=Callagrafx Style\CAS CAN-AM Basic Dock CAL\*.dat"

		SectionEnd
		Section /o "Canal Addon Mod (CAN-AM) - SimGoober Canals" canam2
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\2 Network Features\Water Transport"
			File "@52 Network Features\Water Transport#\Canal Addon Mod#\NetworkAddonMod_CanAM_*.dat"
			File "@52 Network Features\Water Transport#\Canal Addon Mod#\@2-SimGoober Style\CanAM Props SG\*.dat"
			File "@52 Network Features\Water Transport#\Canal Addon Mod#\@2-SimGoober Style\CAS CAN-AM Basic Dock SG\*.dat"
		SectionEnd
		Section /o -dummy canam3
		SectionIn 7
		SectionEnd
	SectionGroupEnd
SectionGroupEnd

SectionGroup /e "Texture Options" textureoptions
	SectionGroup "Road Texture Design" texturemain
		Section "US/NA-RHD" texture1
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\US"
			File "@58 Texture and Drive Side Support\@0=US\*.dat"			
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\US\US_RightSide"
			File "@58 Texture and Drive Side Support\@0=US\@1=US_RightSide\*.dat"
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\US\US_RightSide\LotSupport\Props"
			File "@58 Texture and Drive Side Support\@0=US\@1=US_RightSide\LotSupport\Props\*.dat"
		SectionEnd
		Section /o "US/NA-LHD" texture2
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\US"
			File "@58 Texture and Drive Side Support\@0=US\*.dat"			
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\US\US_LeftSide"
			File "@58 Texture and Drive Side Support\@0=US\@2-US_LeftSide\*.dat"
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\US\US_LeftSide\LotSupport\Props"
			File "@58 Texture and Drive Side Support\@0=US\@2-US_LeftSide\LotSupport\Props\*.dat"
		SectionEnd
		Section /o "EU/INT-RHD" texture3
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\EU"
			File "@58 Texture and Drive Side Support\@1-EU\*.dat"			
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\EU\EU_RightSide"
			File "@58 Texture and Drive Side Support\@1-EU\@1=EU_RightSide\*.dat"
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\EU\EU_RightSide\LotSupport\Props"
			File "@58 Texture and Drive Side Support\@1-EU\@1=EU_RightSide\LotSupport\Props\*.dat"
		SectionEnd
		Section /o "EU/INT-LHD" texture4
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\EU"
			File "@58 Texture and Drive Side Support\@1-EU\*.dat"			
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\EU\EU_LeftSide"
			File "@58 Texture and Drive Side Support\@1-EU\@2-EU_LeftSide\*.dat"
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\EU\EU_LeftSide\LotSupport\Props"
			File "@58 Texture and Drive Side Support\@1-EU\@2-EU_LeftSide\LotSupport\Props\*.dat"
		SectionEnd
	SectionGroupEnd
	SectionGroup "Nightlighting Options" nitemain
		Section "Maxis Nite Props" nite1
			${If} ${SectionIsSelected} ${texture1}
			${OrIf} ${SectionIsSelected} ${texture2}
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\US\US Maxis Nite"
			File "@58 Texture and Drive Side Support\@0=US\@1=US_RightSide\=US Maxis Nite\*.dat"			
			${Else}
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\EU\EU Maxis Nite"
			File "@58 Texture and Drive Side Support\@1-EU\@1=EU_RightSide\=EU Maxis Nite\*.dat"			
			${EndIf}
		SectionEnd
		Section /o "Dark Nite Props" nite2
			${If} ${SectionIsSelected} ${texture1}
			${OrIf} ${SectionIsSelected} ${texture2}
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\US\US Dark Nite"
			File "@58 Texture and Drive Side Support\@0=US\@1=US_RightSide\-US Dark Nite\*.dat"			
			${Else}
			SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\EU\EU Dark Nite"
			File "@58 Texture and Drive Side Support\@1-EU\@1=EU_RightSide\-EU Dark Nite\*.dat"			
			${EndIf}
		SectionEnd
	SectionGroupEnd
	Section /o "Cul-De-Sacs" culdesac
		${If} ${SectionIsSelected} ${texture1}
		${OrIf} ${SectionIsSelected} ${texture2}
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\US\z_Cul-De-Sacs"
		File "@58 Texture and Drive Side Support\@0=US\@3z_Cul-De-Sacs\*.dat"			
		${Else}
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\EU\z_Cul-De-Sacs"
		File "@58 Texture and Drive Side Support\@1-EU\@3z_Cul-De-Sacs\*.dat"			
		${EndIf}
	SectionEnd
	Section /o "Mid/High Density Street Int Islands" islands
		${If} ${SectionIsSelected} ${texture1}
		${OrIf} ${SectionIsSelected} ${texture2}
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\US\z_Mid-High Density Street Intersection Islands"
		File "@58 Texture and Drive Side Support\@0=US\@4!z_Mid-High Density Street Intersection Islands\*.dat"			
		${Else}
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\EU\z_Mid-High Density Street Intersection Islands"
		File "@58 Texture and Drive Side Support\@0=US\@4!z_Mid-High Density Street Intersection Islands\*.dat"			
		${EndIf}
	SectionEnd
	Section "Center Arrows for NWM Turning Lane Avenues (TLA)" tlaarrows
		${If} ${SectionIsSelected} ${texture1}
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\US\US_RightSide\TLA Center Turn Arrows"
		File "@58 Texture and Drive Side Support\@0=US\@1=US_RightSide\TLA Center Turn Arrows\tla_center_arrows_addon_RHD.dat"			
		${ElseIf} ${SectionIsSelected} ${texture2}
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\US\US_LeftSide\TLA Center Turn Arrows"
		File "@58 Texture and Drive Side Support\@0=US\@2-US_LeftSide\TLA Center Turn Arrows\tla_center_arrows_addon_LHD.dat"			
		${ElseIf} ${SectionIsSelected} ${texture3}
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\EU\EU_RightSide\TLA Center Turn Arrows"
		File "@58 Texture and Drive Side Support\@0=US\@1=US_RightSide\TLA Center Turn Arrows\tla_center_arrows_addon_RHD.dat"					
		${Else}
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\8 Texture and Drive Side Support\EU\EU_LeftSide\TLA Center Turn Arrows"
		File "@58 Texture and Drive Side Support\@0=US\@2-US_LeftSide\TLA Center Turn Arrows\tla_center_arrows_addon_LHD.dat"			
		${EndIf}		
	SectionEnd
SectionGroupEnd

SectionGroup /e "!Miscellaneous Options" miscoptions
	Section "Hole Diggers and Ground Raisers" digraise1
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\6 Miscellaneous\Hole Diggers and Ground Raisers"
		File "@56 Miscellaneous\Hole Diggers and Ground Raisers#\Auto-Destruct Lots\*.dat"			
	SectionEnd
	Section /o "Legacy Hole Digger and Ground Raiser Lots" digraise2
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\6 Miscellaneous\Hole Diggers and Ground Raisers"
		File "@56 Miscellaneous\Hole Diggers and Ground Raisers#\!Standard Lots\*.SC4Lot"
	SectionEnd
	Section "Maxis Station, Tollbooth, and Transit Lot Upgrades" maxislot
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\6 Miscellaneous\Maxis Transit Lots"
		File "@56 Miscellaneous\Maxis Transit Lots#\^Maxis Station, Tollbooth, and Transit Lot Upgrades\*.dat"
	SectionEnd
	Section /o "Abandoned Buildings Data View" bldgview
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\5 DataView Options"
		File "@55 DataView Options#\Abandoned Buildings Data View\*.dat"
	SectionEnd	
	Section "Transit Station Data View" stationview
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\5 DataView Options"
		File "@55 DataView Options#\Transit Station Data View\*.dat"
	SectionEnd	
	Section "Zone Data View" zoneview
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\5 DataView Options"
		File "@55 DataView Options#\Zone Data View\*.dat"
	SectionEnd
	
	/*
	SectionGroup "!Maxis Airport Capacity Adjustment" airportmain
	Section "Maxis Airport Capacity-Default Settings" airport1
	SectionEnd
	Section /o "Maxis Airport Capacity-Medium Settings" airport2
	SectionEnd
	Section /o "Maxis Airport Capacity-Large Settings" airport3
	SectionEnd
	SectionGroupEnd
	*/
	
	SectionGroup "!Extended Station Queries" stationquerymain
		Section "Standard Station Queries" stationquery1
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\6 Miscellaneous\Extended Station Queries"
		File "@56 Miscellaneous\Extended Station Queries#\@1=Standard\*.dat"
		SectionEnd
		Section /o "Simple Station Queries" stationquery2
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\6 Miscellaneous\Extended Station Queries"
		File "@56 Miscellaneous\Extended Station Queries#\@2-Simple\*.dat"
		SectionEnd
		Section /o "Wide Station Queries" stationquery3
		SetOutPath "$INSTDIR\Plugins\Network Addon Mod\6 Miscellaneous\Extended Station Queries"
		File "@56 Miscellaneous\Extended Station Queries#\@3-Wide\*.dat"
		SectionEnd
	SectionGroupEnd
SectionGroupEnd

Section -AdditionalIcons
  SetShellVarContext all
  SetOutPath "$INSTDIR"
  WriteIniStr "$INSTDIR\NAM.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  WriteIniStr "$INSTDIR\Simtropolis.url" "InternetShortcut" "URL" "http://www.simtropolis.com"
  WriteIniStr "$INSTDIR\SC4Evermore.url" "InternetShortcut" "URL" "http://www.sc4evermore.com" ; if you only want to install one URL in the start menu, simply remove this line and similar lines below
  CreateDirectory "$SMPROGRAMS\Network Addon Mod" ; the start menu folder
  CreateShortCut "$SMPROGRAMS\Network Addon Mod\Simtropolis.com.lnk" "$INSTDIR\NAM.url"
  CreateShortCut "$SMPROGRAMS\Network Addon Mod\Simtropolis.com.lnk" "$INSTDIR\Simtropolis.url"
  CreateShortCut "$SMPROGRAMS\Network Addon Mod\SC4Devotion.com.lnk" "$INSTDIR\SC4Evermore.url"
  CreateShortCut "$SMPROGRAMS\Network Addon Mod\Uninstall Network Addon Mod.lnk" "$INSTDIR\uninst.exe"
;  SetOutPath "$PROGRAMFILES\Traffic Simulator Configuration Tool"
;  IfFileExists "$PROGRAMFILES\Traffic Simulator Configuration Tool\NAM-TSCT.jar" 0 +3
;  CreateShortCut "$SMPROGRAMS\Network Addon Mod\Traffic Simulator Configuration Tool.lnk" "$PROGRAMFILES\Traffic Simulator Configuration Tool\NAM-TSCT.jar" "" "$PROGRAMFILES\Traffic Simulator Configuration Tool\TSCT_1.ico"
;  CreateShortCut "$DESKTOP\Traffic Simulator Configuration Tool.lnk" "$PROGRAMFILES\Traffic Simulator Configuration Tool\NAM-TSCT.jar" "" "$PROGRAMFILES\Traffic Simulator Configuration Tool\TSCT_1.ico"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

; Oh no, now we've lost SimCity...

Function FindSimCity
  ClearErrors
  ReadRegStr $SC4InstallDir HKLM "Software\Maxis\SimCity 4" "Install Dir"
  IfErrors CheckMore 0
  IfFileExists "$SC4InstallDir\Apps\SimCity 4.exe" FoundIt
CheckMore:
  StrCpy $SC4InstallDir "$PROGRAMFILES\Maxis\SimCity 4\"
  ${DirState} $SC4InstallDir $0 
  ${If} $0 < 1
    StrCpy $SC4InstallDir "$PROGRAMFILES\Maxis\SimCity 4 Deluxe\"
  ${EndIf}
  Strlen $0 $SC4InstallDir
  IntOp $0 $0 - 1
  StrCpy $SC4InstallDir $SC4InstallDir $0            ;Remove trailing slash
  IfFileExists $SC4InstallDir FoundIt
  StrCpy $3 'In the following dialog box, please choose the folder containing your SimCity 4 installation.  It is normally named either "SimCity 4" or "SimCity 4 Deluxe".'
  ${Locate} $PROGRAMFILES /L=F IsSimCity
  StrCmp $R0 "" 0 FixPath
    ${If} $PROGRAMFILES != $PROGRAMFILES64
      ${Locate} $PROGRAMFILES64 /L=F IsSimCity
      StrCmp $R0 "" 0 FixPath
    ${EndIf}
 ;   MessageBox MB_YESNO|MB_ICONQUESTION|MB_DEFBUTTON2 "Are you installing the NAM on this machine so that it can be ported to a Mac?" IDNO GetSC4Folder
    StrCpy $SC4InstallDir ""
    Return
GetSC4Folder:
    MessageBox MB_OK|MB_ICONINFORMATION 'The installer cannot find the SimCity 4 installation folder on your system.  $3'
GetSC4Folder2:
    nsDialogs::SelectFolderDialog "SimCity 4 Folder Dialog" "Please select your SimCity 4 installation folder." $PROGRAMFILES
    StrCpy $SC4InstallDir $0
    StrCmp $SC4InstallDir "" 0 FoundIt
    MessageBox MB_YESNO|MB_ICONQUESTION|MB_DEFBUTTON2 "If you do not select your SimCity 4 installation folder, the installer will have to terminate.$\r$\n$\nDo you wish to terminate the installation?" IDNO GetSC4Folder2
    Quit
FixPath:
  StrCpy $0 $R0
  StrCpy $SC4InstallDir $0 -5                       ;Remove \Apps
FoundIt:
  StrCpy $0 $SC4InstallDir
  System::Call 'kernel32::GetLongPathName(t r0, t .r1, i ${NSIS_MAX_STRLEN}) i .r2'
  StrCmp $2 error +2
  StrCpy $SC4InstallDir $1
  StrCpy $SC4Exec "$SC4InstallDir\Apps\SimCity 4.exe"
  IfFileExists $SC4Exec SC4Exists 0
    MessageBox MB_OK|MB_ICONEXCLAMATION "The file $\"SimCity 4.exe$\" cannot be found in its installation directory.  $3"
    Goto GetSC4Folder2
SC4Exists:
  MoreInfo::GetFileVersion $SC4Exec
  Pop $0
  StrCpy $1 $0 3
  StrCmp $1 "1.0" 0 CheckRH
    MessageBox MB_OK|MB_ICONSTOP "You have the original version of the game installed.  In order to run the NAM, you must have a Version 1.1.641 digital copy of SimCity 4 Deluxe, as available on GOG.com, Steam, or the EA App.  Simply search for $\"Sim City 4 Deluxe Edition$\" at these sites.  When you get the game, install it, and then restart the NAM installer.$\r$\n$\nThe NAM installer will now exit."
    Quit
CheckRH:
  StrCmp $1 "1.1" ValidExec 0
  MessageBox MB_OK|MB_ICONSTOP "Your version of the SimCity 4.exe file does not have the correct header, and may be damaged.  Please reinstall the game, and then restart the NAM installer."
  Quit
ValidExec:
  StrCpy $5 0
  ${Do}
    StrLen $2 $0
    IntOp $2 $2 - 4
    IntOp $2 0 - $2
    StrCpy $1 $0 3 $2
    ${StrStr} $3 $0 "641"
    ${If} $1 < 641
    ${AndIf} $3 == ""
      MessageBox MB_OK|MB_ICONINFORMATION "Your version of SimCity 4 is Version 1.1.640 or earlier, and cannot run the NAM.dll file, which requires a digital copy of Version 1.1.641 (as available on GOG.com, Steam, or the EA App).  The installer will now exit."
      Quit
  ${EndIf}
  Call MemoryPatches
FunctionEnd

Function IsSimCity
  StrCmp $R7 "SimCity 4.exe" +3
NotFound:
    Push 0
    return
  StrCmp $R6 "0" "" NotFound
  StrCpy $R0 $R8
  StrCpy $0 StopLocate
  Push $0
FunctionEnd

Function MemoryPatches
  SetOutPath "$NAMAuxDir\Tools"
  File "4gb_patch.exe"
  ClearErrors
  ReadRegDWORD $5 HKLM "Software\Maxis\SimCity 4" "Large Address Aware"
  ${IfNot} ${AtLeastWin2000}
  ${OrIf} $5 > 0
    Return
  ${EndIf}
  # allocate
  System::Alloc 64  
  Pop $1
  # init
  System::Call "*$1(i64)"
  # call
  System::Call "Kernel32::GlobalMemoryStatusEx(i r1)"
  # get
  System::Call "*$1(i.r2, i.r3, l.r4, l.r5, l.r6, l.r7, l.r8, l.r9, l.r10)"
  # free
  System::Free $1
  System::Int64Op $4 / 1048576
  Pop $Memory
  ${If} ${RunningX64}
  ${OrIf} Wine = 1
    StrCpy $1 4
    StrCpy $2 "This operation is completely harmless, and has no negative side effects."
    StrCpy $4 'Select "OK" to allow the installer to make this change, or "Cancel" to terminate the NAM installation.'
  ${Else}
    StrCpy $1 3
    StrCpy $2 "You are running a 32-bit operating system.  If you have a large Plugins folder, the NAM may cause your game to crash-to-desktop (CTD) upon city loads, due to lack of memory bandwidth.$6$\r$\n$\n"
    StrCpy $4 "Do you still wish to install the NAM?"
  ${EndIf}
  StrCpy $8 '$2$4'
  ${If} ${RunningX64}
    StrCpy $9 $8
  ${EndIf}  
  StrCpy $0 'In order to provide improved stability and functionality, the NAM installer needs to set a flag in your copy of SimCity 4 that will allow it to use up to $1 GB of virtual memory.  (This is different from physical memory, and may be more or less than the amount of your installed physical memory.)  $9'
  ${If} ${RunningX64}
  ${AndIf} $Memory > 1500
    MessageBox MB_OKCANCEL|MB_ICONINFORMATION "$0" IDOK CheckAccountType
    Quit
  ${EndIf}
CheckAccountType:
  UserInfo::GetAccountType
  Pop $1
  ${If} $1 != "Admin"
    MessageBox MB_OK|MB_ICONSTOP|MB_DEFBUTTON2 'Your account does not have the access necessary to perform the needed operations.  In order to allow the NAM installer to perform these operations and install the NAM in the proper place for your account, you need to do the following:$\r$\n$\n1. Log into an account with administrator priviliges.$\r$\n2. Give administrative privileges to this account.$\r$\n3. Log back into this account and run the NAM installer.$\r$\n$\nAfter that, you may remove the administrative priviliges from this account if you want.'
;  Alternatively, you can just proceed with the NAM installation now and not make the stability and functionality patches.  If you wish to make the later, you will need to run the NAM uninstaller and then run the NAM installer again.$\r$\n\nDo you want to continue with the installation without making the stability and functionality improvements?  (WARNING:  If you say "Yes", this may result in occasional crashes or freezes of your game.)'  IDNO +2
;        Return
;        MessageBox MB_OK|MB_ICONINFORMATION "The NAM installer will now exit.  Please add administrative privileges to the current account and restart the NAM installer from this account."
    Quit
  ${EndIf}
Retry4GB:
  ClearErrors
  ExecWait '"$NAMAuxDir\Tools\4gb_patch.exe" $SC4Exec' $0
  IfErrors 0 Check4GB
Error4GB:
    MessageBox MB_ABORTRETRYIGNORE|MB_ICONEXCLAMATION 'The NAM installer was unable to patch your SimCity 4 executable file.  This can happen if the game is currently running.  If that is the case, please exit the game and select "Retry".  Otherwise, select "Abort" to abort the installation, or select "Ignore", and the NAM installation will continue without the patch.' IDRETRY Retry4GB IDIGNORE PatchFailed
    Quit
PatchFailed:
  WriteRegDWORD HKLM "Software\Maxis\SimCity 4" "Large Address Aware" 2
  Return
Check4GB:
  ${If} $0 != 0
    Goto Error4GB
  ${EndIf}
  ${If} ${RunningX64}
  ${OrIf} $Wine = 1
    WriteRegDWORD HKLM "Software\Maxis\SimCity 4" "Large Address Aware" 1
    Return                          ;We're done
  ${EndIf}
  WriteRegDWORD HKLM "Software\Maxis\SimCity 4" "Large Address Aware" 1
FunctionEnd


; Section descriptions, referred by the labels in the Section line
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
;main plugins.
  !insertmacro MUI_DESCRIPTION_TEXT ${sec1} "Core files and features for the Network Addon Mod, including bugfixes, basic intersection, transition, and curve additions, and roundabout functionality."
  !insertmacro MUI_DESCRIPTION_TEXT ${sec3} "The NAM Controller contains all the code necessary to make the NAM's transportation network additions functional. Select the appropriate drive-side version and the texture type for your region. This choice determines whether traffic flows on the right (Right Hand Traffic) or left (Left Hand Traffic) side of the road, which is distinct from whether the vehicle's steering wheel is on the left (Left Hand Drive) or right (Right Hand Drive) side. Typically, Left Hand Traffic is paired with Right Hand Drive vehicles, and Right Hand Traffic with Left Hand Drive vehicles, to allow the driver better visibility of oncoming traffic for safer overtaking."
  !insertmacro MUI_DESCRIPTION_TEXT ${sec4} "These are additional plugins that provide more features and additions."
  !insertmacro MUI_DESCRIPTION_TEXT ${sec10} "Choose one of the Automata Controllers here. Custom Automata Controllers can be created with external tools."
  !insertmacro MUI_DESCRIPTION_TEXT ${sec11} "Choose one of the Traffic Simulators here. Custom Traffic Simulators can be created with external tools."
  !insertmacro MUI_DESCRIPTION_TEXT ${miscoptions} "Miscellanous options for the mod, including Hole Diggers/Ground Raisers, Data View and Query Plugins, and adjustments to Maxis Transit Lots/Airports."

;NAM Controller and Drive Side/Texture Options
  !insertmacro MUI_DESCRIPTION_TEXT ${controller1} "Choose this option only if you have a right hand drive (e.g. US, Italy, Brazil) version of the game and want to use US/North American textures, configuring the game for Right Hand Traffic, where vehicles are typically Left Hand Drive in reality."
  !insertmacro MUI_DESCRIPTION_TEXT ${controller2} "Choose this option only if you have a left hand drive (e.g. UK, Japan, Australia) version of the game and want to use UK/European textures, configuring the game for Left Hand Traffic, where vehicles are typically Right Hand Drive in reality."
;automata plugins
  !insertmacro MUI_DESCRIPTION_TEXT ${auto1} "At a minimum this plugin is required as it adds additional functionality."
  !insertmacro MUI_DESCRIPTION_TEXT ${auto2} "Increases the overall display of Automata so that they appear for most of the 24-hour Sim day."
  !insertmacro MUI_DESCRIPTION_TEXT ${auto3} "Lengthens the amount of time Automata remain visible."
  !insertmacro MUI_DESCRIPTION_TEXT ${auto4} "Increases the overall display of Automata and lengthens the amount of time they remain visible, so that they appear for most of the 24-hour Sim day."
  !insertmacro MUI_DESCRIPTION_TEXT ${auto5} "Signifcantly adjusts the overall display of Automata so that they appear more."
  !insertmacro MUI_DESCRIPTION_TEXT ${auto6} "Signifcantly adjusts the overall display of Automata so that they appear more for most of the 24-hour Sim day."
  !insertmacro MUI_DESCRIPTION_TEXT ${auto7} "Signifcantly adjusts the overall display of Automata and lengthens the amount of time they remain visible, so that they appear more."
  !insertmacro MUI_DESCRIPTION_TEXT ${auto8} "Signifcantly adjusts the overall display of Automata and lengthens the amount of time they remain visible,  so that they appear more for most of the 24-hour Sim day."
  !insertmacro MUI_DESCRIPTION_TEXT ${auto9} "Special version of the Radical Persistent 24-Hour Plugin with optimizations from NAM Team member Lucario Boricua."

;traffic plugins
  !insertmacro MUI_DESCRIPTION_TEXT ${capa1} "Sets per-tile network capacities to the following:$\r$\n\
$\r$\nStreet: 750$\r$\nRoad: 1200$\r$\nAvenue: 1200$\r$\nOne-Way Road: 1800$\r$\nHighway: 3750$\r$\nRHW: 3000$\r$\nRail: 6250$\r$\nSubway: 5000$\r$\nLight Rail: 5000$\r$\nMonorail: 5000"
  !insertmacro MUI_DESCRIPTION_TEXT ${capa2} "Sets per-tile network capacities to the following:$\r$\n\
$\r$\nStreet: 1500$\r$\nRoad: 2400$\r$\nAvenue: 2400$\r$\nOne-Way Road: 3600$\r$\nHighway: 7500$\r$\nRHW: 6000$\r$\nRail: 12500$\r$\nSubway: 10000$\r$\nLight Rail: 10000$\r$\nMonorail: 10000"
  !insertmacro MUI_DESCRIPTION_TEXT ${capa3} "Sets per-tile network capacities to the following:$\r$\n\
$\r$\nStreet: 2400$\r$\nRoad: 4000$\r$\nAvenue: 4000$\r$\nOne-Way Road: 6000$\r$\nHighway: 12500$\r$\nRHW: 10000$\r$\nRail: 20000$\r$\nSubway: 16000$\r$\nLight Rail: 16000$\r$\nMonorail: 16000"
  !insertmacro MUI_DESCRIPTION_TEXT ${capa4} "Sets per-tile network capacities to the following:$\r$\n\
$\r$\nStreet: 3600$\r$\nRoad: 6000$\r$\nAvenue: 6000$\r$\nOne-Way Road: 9000$\r$\nHighway: 18750$\r$\nRHW: 15000$\r$\nRail: 30000$\r$\nSubway: 30000$\r$\nLight Rail: 30000$\r$\nMonorail: 30000"
  !insertmacro MUI_DESCRIPTION_TEXT ${capa5} "Sets per-tile network capacities to the following:$\r$\n\
$\r$\nStreet: 7200$\r$\nRoad: 12000$\r$\nAvenue: 12000$\r$\nOne-Way Road: 18000$\r$\nHighway: 37500$\r$\nRHW: 30000$\r$\nRail: 65200$\r$\nSubway: 65200$\r$\nLight Rail: 65200$\r$\nMonorail: 65200"

;network features
  !insertmacro MUI_DESCRIPTION_TEXT ${roamain} "Various addons for the game's surface roadway networks--Street, Road, One-Way Road, and Avenue."
  !insertmacro MUI_DESCRIPTION_TEXT ${roavia1} "Installs Draggable Elevated Viaducts for the Road, One-Way Road, and Avenue networks, at two height levels, Level 1 (7.5m) and Level 2 (15m)."
  !insertmacro MUI_DESCRIPTION_TEXT ${roavia2} "Installs Legacy Puzzle Piece Elevated Viaducts for the Road, One-Way Road, and Avenue networks.  Not installing this option will only result in the menu button being hidden, and existing puzzle-based viaducts will remain in place."
  !insertmacro MUI_DESCRIPTION_TEXT ${roavia3} "Installs the Alternate Elevated Viaducts, which include limited-functionality alternate styles for the Road Viaducts, and some support for Street/SAM Viaducts."
  !insertmacro MUI_DESCRIPTION_TEXT ${nwmturn} "Installs the Network Widening Mod (NWM), which includes override networks, consisting of wider (and narrower) versions of the Road, One-Way Road, and Avenue networks."
  !insertmacro MUI_DESCRIPTION_TEXT ${ftl} "Installs the Flexible Turn Lanes (FTLs) and QuickTurn systems, allowing for draggable/semi-draggable customizable turn lane configurations at intersections, as well as the Signalized Intersection and Turn Arrow Project (SITAP) for One-Way Roads."
  !insertmacro MUI_DESCRIPTION_TEXT ${tulep} "Installs the legacy Turn Lane Extension Pieces (TuLEPs), the puzzle piece-based precursor to the FTL system.  Only recommended for long-time advanced users who really have to have them."
  !insertmacro MUI_DESCRIPTION_TEXT ${rew} "Installs the RealExpressway (REW) system, which adds ramp functionality to the One-Way Road network.  Requires that the Network Widening Mod be installed."
  !insertmacro MUI_DESCRIPTION_TEXT ${atl} "Installs the Legacy Automatic Avenue Turn Lanes, which draws turn lanes at Orthogonal x Orthogonal (OxO) 4-Way Avenue x Avenue intersections.  May cause instability with NWM, FTL, and Draggable Viaduct features."
  !insertmacro MUI_DESCRIPTION_TEXT ${rtl} "Installs the Legacy Semi-Automatic Road Turn Lanes, which draws turn lanes at Orthogonal x Orthogonal (OxO) 3-Way and 4-Way Road x Road intersections when overclicked with the One-Way Road tool."
  !insertmacro MUI_DESCRIPTION_TEXT ${sammain} "Installs the Street Addon Mod (SAM), which offers override networks for different styles of the Street network, i.e., red brick, dirt, gravel, etc."
  !insertmacro MUI_DESCRIPTION_TEXT ${rurp} "Installs the Rural Roads Plugin (RuRP), which includes cosmetic puzzle pieces for more rural appearances (including passing zones) for the Road network."
  !insertmacro MUI_DESCRIPTION_TEXT ${widecrn} "Installs the Wide Corner Intersection option, which widens the radius of Diagonal x Diagonal (DxD) intersections for the Road and One-Way Road networks."
  !insertmacro MUI_DESCRIPTION_TEXT ${owrarrowmain} "Installs optional plugins that affect the display of the directional arrows on the One-Way Road network."
  !insertmacro MUI_DESCRIPTION_TEXT ${owrarrow1} "Retains the default visible double directional arrows on the One-Way Road network."
  !insertmacro MUI_DESCRIPTION_TEXT ${owrarrow2} "Eliminates the directional arrows on the One-Way Road network."
  !insertmacro MUI_DESCRIPTION_TEXT ${owrarrow3} "Turns the directional arrows on the One-Way Road network to an overlay that is invisible unless highlighted with a Query Tool."
  !insertmacro MUI_DESCRIPTION_TEXT ${owrarrow4} "Replaces the default double directional arrows with a single directional arrow."
  !insertmacro MUI_DESCRIPTION_TEXT ${streetbridgemain} "Installs additional bridges for the Street network."
  !insertmacro MUI_DESCRIPTION_TEXT ${roadbridgemain} "Installs additional bridges for the Road network."
  !insertmacro MUI_DESCRIPTION_TEXT ${owrbridgemain} "Installs additional bridges for the One-Way Road network."
  !insertmacro MUI_DESCRIPTION_TEXT ${avebridgemain} "Installs additional bridges for the Avenue network."
  !insertmacro MUI_DESCRIPTION_TEXT ${nwmbridgemain} "Installs additional bridges for the Network Widening Mod (NWM) family of override networks."
  !insertmacro MUI_DESCRIPTION_TEXT ${sambridgemain} "Installs additional bridges for the Street Addon Mod (SAM) family of override networks."
  !insertmacro MUI_DESCRIPTION_TEXT ${rail} "Various options for the Rail network."
  !insertmacro MUI_DESCRIPTION_TEXT ${rrw} "Installs the RealRailway (RRW) standard for the Rail network, an integral part of the NAM's railway implementation."
  !insertmacro MUI_DESCRIPTION_TEXT ${rrwpre} "Installs RRW-style textures to cover Legacy Maxis Rail situations that are not possible with the RRW."
  !insertmacro MUI_DESCRIPTION_TEXT ${rrwslopemain} "Installs the slope mod settings for the RRW/Rail Network.  Required, as the RRW uses new tunnel portals."
  !insertmacro MUI_DESCRIPTION_TEXT ${rrwslope1} "Installs settings equivalent to the Maxis defaults."
  !insertmacro MUI_DESCRIPTION_TEXT ${rrwslope2} "Installs moderate slope settings."
  !insertmacro MUI_DESCRIPTION_TEXT ${rrwslope3} "Installs moderate strict settings."
  !insertmacro MUI_DESCRIPTION_TEXT ${urail} "Installs the Underground Rail (URail) system, which consists of a comprehensive series of puzzle pieces for construction of subsurface Rail networks (including under other networks)."
  !insertmacro MUI_DESCRIPTION_TEXT ${railbridgemain} "Installs additional bridges for the Rail network and its overrides."
  !insertmacro MUI_DESCRIPTION_TEXT ${rhw} "Installs the RealHighway (RHW) system, a comprehensive new system of Highway networks with modular interchange functionality and variable widths."
  !insertmacro MUI_DESCRIPTION_TEXT ${rhwbase} "Installs the RealHighway (RHW) base network tool and features."
  !insertmacro MUI_DESCRIPTION_TEXT ${rhwreg} "Installs a Regional Transport View plugin that allows RHW networks to appear.  This requires opening the Traffic Data View prior to saving a city in order for the RHW to appear."
  !insertmacro MUI_DESCRIPTION_TEXT ${rhwbrt} "Installs Lot-based traffic filters to allow for the construction of Bus Rapid Transit (BRT) systems using the RHW network." 
  !insertmacro MUI_DESCRIPTION_TEXT ${rhwcp} "Installs the RHW Cosmetic Pieces, an extensive series of puzzle pieces designed to allow tile-by-tile customization of RHW markings."
  !insertmacro MUI_DESCRIPTION_TEXT ${rhwlegacy} "Installs main Legacy Support for older RHW systems, including those built prior to NAM 31 (2013) and even those dating back to the initial Version 1.x releases of the old Rural Highway Mod plugin."
  !insertmacro MUI_DESCRIPTION_TEXT ${rhwpuzzle} "Installs the Legacy Puzzle Pieces for the RHW, which have been superseded with newer draggable/FLEX components.  Existing puzzle pieces will remain in place; this only affects access to the menu button to place them."
  !insertmacro MUI_DESCRIPTION_TEXT ${rhwflupleg} "Installs the Legacy Puzzle Pieces for the RHW Flexible Underpasses (FLUPs).  The newer, experimental Subway-based implementation can be found under the Subway and Underground options."
  !insertmacro MUI_DESCRIPTION_TEXT ${rhwbridgemain} "Installs  bridges for the RHW system."
  !insertmacro MUI_DESCRIPTION_TEXT ${ped} "Installs additional options for Pedestrian Transport, including Pedestrian Malls and Crosswalks."
  !insertmacro MUI_DESCRIPTION_TEXT ${ped1} "Installs the Pedestrian Revolution Mod (PRM) Draggable Pedestrian Malls, which include several different styles of pedestrian malls, trails, and walkways."
  !insertmacro MUI_DESCRIPTION_TEXT ${ped2} "Installs the PedMall and PedOverpass Puzzle Pieces."
  !insertmacro MUI_DESCRIPTION_TEXT ${midblock} "Installs the Pedestrian Revolution Mod (PRM) Midblock Crosswalks."
  !insertmacro MUI_DESCRIPTION_TEXT ${pedbridgemain} "Installs bridges for the PedMall system."
  !insertmacro MUI_DESCRIPTION_TEXT ${hrw} "Installs the Hybrid Railway (HRW) system, a dual-service Rail-type network that supports both regular Rail traffic and High-Speed Rail traffic (at a lower speed)."
  !insertmacro MUI_DESCRIPTION_TEXT ${lightrail} "Installs options for Light Rail network, including Ground Light Rail/Tram and Dual-Networking Options."
  !insertmacro MUI_DESCRIPTION_TEXT ${glr1} "Installs Draggable Ground Light Rail (GLR), a ground-level version of the Elevated Light Rail network."
  !insertmacro MUI_DESCRIPTION_TEXT ${glr2} "Installs the older Ground Light Rail (GLR) Puzzle Pieces." 
  !insertmacro MUI_DESCRIPTION_TEXT ${glr3} "Installs two additional styles for Draggable Ground Light Rail (GLR), with swappable/customizable base textures." 
  !insertmacro MUI_DESCRIPTION_TEXT ${elrdual} "Installs dual-networking features for Elevated Light Rail-over-Road, Avenue, and the NWM's Road-4 network, in puzzle piece and FLEX Piece form." 
  !insertmacro MUI_DESCRIPTION_TEXT ${glrdual} "Installs dual-networking features for Ground Light Rail (Tram)-in/on-Road, Avenue, and Street, in puzzle piece and semi-draggable form." 
  !insertmacro MUI_DESCRIPTION_TEXT ${highelr} "Installs Double-Height (30.5m) Elevated Light Rail puzzle pieces.  Note that this feature will not receive any future additions." 
  !insertmacro MUI_DESCRIPTION_TEXT ${lightrailbridgemain} "Installs additional bridges for the Light Rail/Tram family of networks."
  !insertmacro MUI_DESCRIPTION_TEXT ${monorail} "Installs additional options for the Monorail network, including override networks." 
  !insertmacro MUI_DESCRIPTION_TEXT ${hsrp} "Installs the (semi-deprecated) High Speed Rail Project (HSRP), consisting of elevated and ground-level Monorail-based override networks, for creating high-speed rail systems." 
  !insertmacro MUI_DESCRIPTION_TEXT ${highmon} "Installs Double-Height (30.5m) Monorail puzzle pieces.  Note that this feature will not receive any future additions." 
  !insertmacro MUI_DESCRIPTION_TEXT ${monorailbridgemain} "Installs additional bridges for the Monorail networks."
  !insertmacro MUI_DESCRIPTION_TEXT ${mhw} "Installs additional options for the game's default (Maxis) Highway networks, including reskins." 
  !insertmacro MUI_DESCRIPTION_TEXT ${mhw1} "Installs additional interchanges and wide-radius curves for the default Maxis Highway (MHW) system."
  !insertmacro MUI_DESCRIPTION_TEXT ${mhw2} "Installs the Maxis Highway Override (MHO) system, which reskins the default Maxis Highways to match more with the RealHighway (RHW) system, and adds modular interchange support.  Requires the RHW be installed." 
  !insertmacro MUI_DESCRIPTION_TEXT ${mhwbridgemain} "Installs additional bridges for the Maxis Highway networks, according to the selections set above." 
  !insertmacro MUI_DESCRIPTION_TEXT ${subflups} "Installs options related to the Subway network and Flexible Underpass (FLUPs) system." 
  !insertmacro MUI_DESCRIPTION_TEXT ${flups1} "Installs the puzzle piece version of the Flexible Underpasses (FLUPs)." 
  !insertmacro MUI_DESCRIPTION_TEXT ${flups2} "Installs the experimental Subway-based draggable version of the Flexible Underpasses (FLUPs)."
  !insertmacro MUI_DESCRIPTION_TEXT ${watertransport} "Installs options related to water transport, namely the Canal Addon Mod (CAN-AM)." 
  !insertmacro MUI_DESCRIPTION_TEXT ${canam1} "Installs the Canal Addon Mod (CAN-AM), which allows for functional canals.  This option is designed to work with the Callagrafx Canals (downloaded separately from SC4Evermore)." 
  !insertmacro MUI_DESCRIPTION_TEXT ${canam2} "Installs the Canal Addon Mod (CAN-AM), which allows for functional canals.  This option is designed to work with the SimGoober Canals (downloaded separately from SC4Evermore)."
  
;bridge options

;textureoptions
  !insertmacro MUI_DESCRIPTION_TEXT ${textureoptions} "Allows selection of texture options and choice of nightlighting mode for select props."
  !insertmacro MUI_DESCRIPTION_TEXT ${texturemain} "Allows selection of road marking types."
  !insertmacro MUI_DESCRIPTION_TEXT ${texture1} "Installs US/North American textures, with yellow centerlines on roadways, with vehicles driving on the right."
  !insertmacro MUI_DESCRIPTION_TEXT ${texture2} "Installs US/North American textures, with yellow centerlines on roadways, with vehicles driving on the left."
  !insertmacro MUI_DESCRIPTION_TEXT ${texture3} "Installs EU/International textures, with white centerlines on roadways, with vehicles driving on the right."
  !insertmacro MUI_DESCRIPTION_TEXT ${texture4} "Installs EU/International textures, with white centerlines on roadways, with vehicles driving on the left."
  !insertmacro MUI_DESCRIPTION_TEXT ${nite1} "Installs Maxis Nite versions of props with nightlighting (like the game's default)."
  !insertmacro MUI_DESCRIPTION_TEXT ${nite2} "Installs Dark Nite versions of props with nightlighting, intended for use with Dark Nite mods by SimFox or Gizmo28."
  !insertmacro MUI_DESCRIPTION_TEXT ${culdesac} "Places cul-de-sacs on the orthogonal end stubs of the Road and Street networks."
  !insertmacro MUI_DESCRIPTION_TEXT ${islands} "Places concrete divider islands between the lanes at Street intersections in Medium and High Density Zones."
  !insertmacro MUI_DESCRIPTION_TEXT ${tlaarrows} "Places arrow markings in the center turn lanes of the Turning Lane Avenues (TLAs) from the Network Widening Mod (NWM).  Requires the NWM be selected as an install option."

;miscellaneous options
  !insertmacro MUI_DESCRIPTION_TEXT ${digraise1} "Installs the NAM's self-destructing Hole Digger and Raiser system, allowing for precise control of terrain adjustments by specific increments." 
  !insertmacro MUI_DESCRIPTION_TEXT ${digraise2} "Installs a set of the legacy, older-style Lot-based Hole Diggers and Raisers." 
  !insertmacro MUI_DESCRIPTION_TEXT ${maxislot} "Installs improvements to the Maxis Transit Lots, including Transit Stations and Tollbooths." 
  !insertmacro MUI_DESCRIPTION_TEXT ${airportmain} "Installs different capacity options for the Maxis Airports." 
  !insertmacro MUI_DESCRIPTION_TEXT ${airport1} "Retains the default Maxis Airport capacity settings." 
  !insertmacro MUI_DESCRIPTION_TEXT ${airport2} "Raises the Maxis Airport capacity settings by a moderate degree." 
  !insertmacro MUI_DESCRIPTION_TEXT ${airport3} "Raises the Maxis Airport capacity settings by a large degree." 
  !insertmacro MUI_DESCRIPTION_TEXT ${stationquerymain} "Installs different Transit Station Query options." 
  !insertmacro MUI_DESCRIPTION_TEXT ${stationquery1} "Retains the standard Transport Station Query." 
  !insertmacro MUI_DESCRIPTION_TEXT ${stationquery2} "Installs a simple version of the Transport Station Query." 
  !insertmacro MUI_DESCRIPTION_TEXT ${stationquery3} "Installs a wider version of the Transport Station Query." 
  !insertmacro MUI_DESCRIPTION_TEXT ${bldgview} "Replaces the Radiation Data View with an Abandoned Buildings Data View, showing where buildings have been abandoned in a city." 
  !insertmacro MUI_DESCRIPTION_TEXT ${stationview} "Improves the display of Transit Stations on the Traffic Data Views." 
  !insertmacro MUI_DESCRIPTION_TEXT ${zoneview} "Improves the game's Zone Data View to better show Transit Stations." 


!insertmacro MUI_FUNCTION_DESCRIPTION_END

Function .onInit
  ; !insertmacro SetSectionFlag ${sec11} ${SF_RO}

  StrCpy $1 ${controller1} ; Group 1 - Option 1 is selected by default
  StrCpy $2 ${capa2} ; Group 2 - Option 2 is selected by default
  StrCpy $3 ${auto3} ; Group 3 - Option 3 is selected by default
  StrCpy $4 ${owrarrow1} ; Group 4 - Option 1 is selected by default
  StrCpy $5 ${mhw1} ; Group 5 - Option 1 is selected by default
  StrCpy $6 ${canam2} ; Group 6 - Option 2 is selected by default
  StrCpy $7 ${texture1} ; Group 7 - Option 1 is selected by default
  StrCpy $8 ${nite1} ; Group 8 - Option 1 is selected by default  
 ; StrCpy $9 ${airport1} ; Group 9 - Option 1 is selected by default
  StrCpy $9 ${stationquery1} ; Group 9 - Option 1 is selected by default
 
  ;prevents Traffic Simulator SectionGroup checkbox from doing anything
  
  StrCpy $NAMAuxDir "$DOCUMENTS\SimCity 4\NAM Auxiliary Files"
  StrCpy $OSLang 0
  StrCpy $SC4Docs $DOCUMENTS
  StrCpy $SC4InstallDir ""
  StrCpy $Wine 0


FunctionEnd

Function .onSelChange

  !insertmacro StartRadioButtons $1
    !insertmacro RadioButton ${controller1}
    !insertmacro RadioButton ${controller2}
  !insertmacro EndRadioButtons

  !insertmacro StartRadioButtons $2
    !insertmacro RadioButton ${capa1}
    !insertmacro RadioButton ${capa2}
    !insertmacro RadioButton ${capa3}
    !insertmacro RadioButton ${capa4}
    !insertmacro RadioButton ${capa5}
  !insertmacro EndRadioButtons
  
  !insertmacro StartRadioButtons $3
    !insertmacro RadioButton ${auto1}
    !insertmacro RadioButton ${auto2}
    !insertmacro RadioButton ${auto3}
    !insertmacro RadioButton ${auto4}
    !insertmacro RadioButton ${auto5}
    !insertmacro RadioButton ${auto6}
    !insertmacro RadioButton ${auto7}
    !insertmacro RadioButton ${auto8}
    !insertmacro RadioButton ${auto9}
  !insertmacro EndRadioButtons
  
  !insertmacro StartRadioButtons $4
    !insertmacro RadioButton ${owrarrow1}
    !insertmacro RadioButton ${owrarrow2}
    !insertmacro RadioButton ${owrarrow3}
    !insertmacro RadioButton ${owrarrow4}
  !insertmacro EndRadioButtons
  
  !insertmacro StartRadioButtons $5
    !insertmacro RadioButton ${mhw1}
    !insertmacro RadioButton ${mhw2}
  !insertmacro EndRadioButtons
  
  !insertmacro StartRadioButtons $6
    !insertmacro RadioButton ${canam1}
    !insertmacro RadioButton ${canam2}
  !insertmacro EndRadioButtons
  
  !insertmacro StartRadioButtons $7
    !insertmacro RadioButton ${texture1}
    !insertmacro RadioButton ${texture2}
    !insertmacro RadioButton ${texture3}
    !insertmacro RadioButton ${texture4}
  !insertmacro EndRadioButtons

  !insertmacro StartRadioButtons $8
    !insertmacro RadioButton ${nite1}
    !insertmacro RadioButton ${nite2}
  !insertmacro EndRadioButtons
  
 /* !insertmacro StartRadioButtons $9
    !insertmacro RadioButton ${airport1}
    !insertmacro RadioButton ${airport2}
    !insertmacro RadioButton ${airport3}
  !insertmacro EndRadioButtons
 */
  !insertmacro StartRadioButtons $9
    !insertmacro RadioButton ${stationquery1}
    !insertmacro RadioButton ${stationquery2}
    !insertmacro RadioButton ${stationquery3}
  !insertmacro EndRadioButtons
  
; 	reinforcement to prevent undesirable default NSIS behavior when clicking SectionGroups
;	for Controller Section
/*
	${If} ${SectionIsSelected} ${sec3}
		SectionSetFlags ${controller1} 1
		SectionSetFlags ${controller2} 0
		SectionSetFlags ${controller3} 0
	${EndIf}
	${If} ${SectionIsSelected} ${controller1}
		SectionSetFlags ${controller1} 1
		SectionSetFlags ${controller2} 0
		SectionSetFlags ${controller3} 0

	${EndIf}
	${If} ${SectionIsSelected} ${controller2}
		SectionSetFlags ${controller1} 0
		SectionSetFlags ${controller2} 1
		SectionSetFlags ${controller3} 0
	${EndIf}*/
;	for Traffic Simulator Section

	${If} ${SectionIsSelected} ${sec11}
		SectionSetFlags ${capa1} 0
		SectionSetFlags ${capa2} 1
		SectionSetFlags ${capa3} 0
		SectionSetFlags ${capa4} 0
		SectionSetFlags ${capa5} 0

	${EndIf}
	${If} ${SectionIsSelected} ${capa2}
		SectionSetFlags ${capa1} 0
		SectionSetFlags ${capa2} 1
		SectionSetFlags ${capa3} 0
		SectionSetFlags ${capa4} 0
		SectionSetFlags ${capa5} 0
	${EndIf}
	
;	for Automata Plugin Section
	${If} ${SectionIsSelected} ${sec10}
		SectionSetFlags ${auto1} 0
		SectionSetFlags ${auto2} 0
		SectionSetFlags ${auto3} 1
		SectionSetFlags ${auto4} 0
		SectionSetFlags ${auto5} 0
		SectionSetFlags ${auto6} 0
		SectionSetFlags ${auto7} 0
		SectionSetFlags ${auto8} 0
		SectionSetFlags ${auto9} 0
	${EndIf}
	${If} ${SectionIsSelected} ${auto3}
		SectionSetFlags ${auto1} 0
		SectionSetFlags ${auto2} 0
		SectionSetFlags ${auto3} 1
		SectionSetFlags ${auto4} 0
		SectionSetFlags ${auto5} 0
		SectionSetFlags ${auto6} 0
		SectionSetFlags ${auto7} 0
		SectionSetFlags ${auto8} 0
		SectionSetFlags ${auto9} 0	
	${EndIf}
	
	;for OWR Arrow Section
	${If} ${SectionIsSelected} ${owrarrowmain}
		SectionSetFlags ${owrarrow1} 1
		SectionSetFlags ${owrarrow2} 0
		SectionSetFlags ${owrarrow3} 0
		SectionSetFlags ${owrarrow4} 0
	${EndIf}
	${If} ${SectionIsSelected} ${owrarrow1}
		SectionSetFlags ${owrarrow2} 0
		SectionSetFlags ${owrarrow3} 0
		SectionSetFlags ${owrarrow4} 0
	${EndIf}
	${If} ${SectionIsSelected} ${owrarrow2}
		SectionSetFlags ${owrarrow1} 0
		SectionSetFlags ${owrarrow3} 0
		SectionSetFlags ${owrarrow4} 0
	${EndIf}
	${If} ${SectionIsSelected} ${owrarrow3}
		SectionSetFlags ${owrarrow1} 0
		SectionSetFlags ${owrarrow2} 0
		SectionSetFlags ${owrarrow4} 0
	${EndIf}
	${If} ${SectionIsSelected} ${owrarrow4}
		SectionSetFlags ${owrarrow1} 0
		SectionSetFlags ${owrarrow2} 0
		SectionSetFlags ${owrarrow3} 0
	${EndIf}
	
	;for CAN-AM Section
	${If} ${SectionIsSelected} ${watertransport}
		SectionSetFlags ${canam1} 0
		SectionSetFlags ${canam2} 0
		SectionSetFlags ${canam3} 0
	${EndIf}
/*	
	;for Airport Capacity Section
	${If} ${SectionIsSelected} ${airportmain}
		SectionSetFlags ${airport1} 1
		SectionSetFlags ${airport2} 0
		SectionSetFlags ${airport3} 0
	${EndIf}
	${If} ${SectionIsSelected} ${airport1}
		SectionSetFlags ${airport2} 0
		SectionSetFlags ${airport3} 0
	${EndIf}
	${If} ${SectionIsSelected} ${airport2}
		SectionSetFlags ${airport1} 0
		SectionSetFlags ${airport3} 0
	${EndIf}
	${If} ${SectionIsSelected} ${airport3}
		SectionSetFlags ${airport1} 0
		SectionSetFlags ${airport2} 0
	${EndIf}
*/
	;for StationQuery Section
	${If} ${SectionIsSelected} ${stationquerymain}
		SectionSetFlags ${stationquery1} 1
		SectionSetFlags ${stationquery2} 0
		SectionSetFlags ${stationquery3} 0
	${EndIf}
	${If} ${SectionIsSelected} ${stationquery1}
		SectionSetFlags ${stationquery2} 0
		SectionSetFlags ${stationquery3} 0
	${EndIf}
	${If} ${SectionIsSelected} ${stationquery2}
		SectionSetFlags ${stationquery1} 0
		SectionSetFlags ${stationquery3} 0
	${EndIf}
	${If} ${SectionIsSelected} ${stationquery3}
		SectionSetFlags ${stationquery1} 0
		SectionSetFlags ${stationquery2} 0
	${EndIf}

	;for Texture Section
	${If} ${SectionIsSelected} ${texturemain}
		SectionSetFlags ${texture1} 1
		SectionSetFlags ${texture2} 0
		SectionSetFlags ${texture3} 0
		SectionSetFlags ${texture4} 0
	${EndIf}
	${If} ${SectionIsSelected} ${texture1}
		SectionSetFlags ${texture2} 0
		SectionSetFlags ${texture3} 0
		SectionSetFlags ${texture4} 0
	${EndIf}
	${If} ${SectionIsSelected} ${texture2}
		SectionSetFlags ${texture1} 0
		SectionSetFlags ${texture3} 0
		SectionSetFlags ${texture4} 0
	${EndIf}
	${If} ${SectionIsSelected} ${texture3}
		SectionSetFlags ${texture1} 0
		SectionSetFlags ${texture2} 0
		SectionSetFlags ${texture4} 0
	${EndIf}
	${If} ${SectionIsSelected} ${texture4}
		SectionSetFlags ${texture1} 0
		SectionSetFlags ${texture2} 0
		SectionSetFlags ${texture3} 0
	${EndIf}


	
	;enforce RHW base tool being installed to select other RHW features

	${If} ${SectionIsSelected} ${rhwreg}
		SectionSetFlags ${rhwbase} 1
	${EndIf}
	${If} ${SectionIsSelected} ${rhwcp}
		SectionSetFlags ${rhwbase} 1
	${EndIf}
	${If} ${SectionIsSelected} ${rhwbrt}
		SectionSetFlags ${rhwbase} 1
	${EndIf}
	${If} ${SectionIsSelected} ${rhwlegacy}
		SectionSetFlags ${rhwbase} 1
	${EndIf}
	${If} ${SectionIsSelected} ${rhwpuzzle}
		SectionSetFlags ${rhwbase} 1
	${EndIf}
	${If} ${SectionIsSelected} ${rhwflupleg}
		SectionSetFlags ${rhwbase} 1
	${EndIf}
	${If} ${SectionIsSelected} ${rhwbridgemain}
		SectionSetFlags ${rhwbase} 1
	${EndIf}

	
	;enforce Draggable GLR being installed to install Extended Draggable GLR
	${If} ${SectionIsSelected} ${glr3}
		SectionSetFlags ${glr1} 1
	${EndIf}
	
	;radio buttons for RRW Slope (since we've otherwise run out of variables for them)
	/*
	SectionSetFlags ${rrwslope1} 0
	SectionSetFlags ${rrwslope2} 1
	SectionSetFlags ${rrwslope3} 0

	${If} ${SectionIsSelected} ${rrwslope1}
		SectionSetFlags ${rrwslope2} 0
		SectionSetFlags ${rrwslope3} 0
	${EndIf}
	${If} ${SectionIsSelected} ${rrwslope2}
		SectionSetFlags ${rrwslope1} 0
		SectionSetFlags ${rrwslope3} 0
	${EndIf}
	${If} ${SectionIsSelected} ${rrwslope3}
		SectionSetFlags ${rrwslope1} 0
		SectionSetFlags ${rrwslope2} 0
	${EndIf}
	*/
	
	;enforce NWM requirement for TLA arrows
	/*${If} ${SectionIsSelected} ${tlaarrows}
		SectionSetFlags ${nwm} 1
	${EndIf}*/
	
	

FunctionEnd
Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Would you like to uninstall $(^Name) and all of its components?" IDYES +2
  Abort
FunctionEnd

Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully uninstalled."
FunctionEnd

Section "un.Uninstall"
  SetShellVarContext all
  Delete $INSTDIR\Plugins\NAM.dll
  RMDir /r "$INSTDIR\Plugins\Network Addon Mod"
  RMDir /r "$SMPROGRAMS\Network Addon Mod"
  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  SetAutoClose true
SectionEnd